/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.ui.internal;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.htwdd.sf.beleg.s86320s86372.BelegRuntimeModule;
import de.htwdd.sf.beleg.s86320s86372.ui.BelegUiModule;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import org.apache.log4j.Logger;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.shared.SharedStateModule;
import org.eclipse.xtext.util.Modules2;
import org.osgi.framework.BundleContext;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class S86320s86372Activator extends AbstractUIPlugin {

	public static final String PLUGIN_ID = "de.htwdd.sf.beleg.s86320s86372.ui";
	public static final String DE_HTWDD_SF_BELEG_S86320S86372_BELEG = "de.htwdd.sf.beleg.s86320s86372.Beleg";
	
	private static final Logger logger = Logger.getLogger(S86320s86372Activator.class);
	
	private static S86320s86372Activator INSTANCE;
	
	private Map<String, Injector> injectors = Collections.synchronizedMap(new HashMap<>(2));
	
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
	}
	
	@Override
	public void stop(BundleContext context) throws Exception {
		injectors.clear();
		INSTANCE = null;
		super.stop(context);
	}
	
	public static S86320s86372Activator getInstance() {
		return INSTANCE;
	}
	
	public Injector getInjector(String language) {
		synchronized (injectors) {
			Injector injector = injectors.get(language);
			if (injector == null) {
				injectors.put(language, injector = createInjector(language));
			}
			return injector;
		}
	}
	
	protected Injector createInjector(String language) {
		try {
			com.google.inject.Module runtimeModule = getRuntimeModule(language);
			com.google.inject.Module sharedStateModule = getSharedStateModule();
			com.google.inject.Module uiModule = getUiModule(language);
			com.google.inject.Module mergedModule = Modules2.mixin(runtimeModule, sharedStateModule, uiModule);
			return Guice.createInjector(mergedModule);
		} catch (Exception e) {
			logger.error("Failed to create injector for " + language);
			logger.error(e.getMessage(), e);
			throw new RuntimeException("Failed to create injector for " + language, e);
		}
	}
	
	protected com.google.inject.Module getRuntimeModule(String grammar) {
		if (DE_HTWDD_SF_BELEG_S86320S86372_BELEG.equals(grammar)) {
			return new BelegRuntimeModule();
		}
		throw new IllegalArgumentException(grammar);
	}
	
	protected com.google.inject.Module getUiModule(String grammar) {
		if (DE_HTWDD_SF_BELEG_S86320S86372_BELEG.equals(grammar)) {
			return new BelegUiModule(this);
		}
		throw new IllegalArgumentException(grammar);
	}
	
	protected com.google.inject.Module getSharedStateModule() {
		return new SharedStateModule();
	}
	
	
}
