/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.ui.tests;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s86320s86372.ui.internal.S86320s86372Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class BelegUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return S86320s86372Activator.getInstance().getInjector("de.htwdd.sf.beleg.s86320s86372.Beleg");
	}

}
