/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBelegScopeProvider extends DelegatingScopeProvider {
}
