/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.serializer;

import com.google.inject.Inject;
import de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Goal;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Model;
import de.htwdd.sf.beleg.s86320.s86372.beleg.S;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Story;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Title;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Use;
import de.htwdd.sf.beleg.s86320.s86372.beleg.XPart;
import de.htwdd.sf.beleg.s86320.s86372.beleg.YPart;
import de.htwdd.sf.beleg.s86320.s86372.beleg.ZPart;
import de.htwdd.sf.beleg.s86320.s86372.services.BelegGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class BelegSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private BelegGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == BelegPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case BelegPackage.GOAL:
				sequence_Goal(context, (Goal) semanticObject); 
				return; 
			case BelegPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case BelegPackage.S:
				sequence_S(context, (S) semanticObject); 
				return; 
			case BelegPackage.STORY:
				sequence_Story(context, (Story) semanticObject); 
				return; 
			case BelegPackage.TITLE:
				sequence_Title(context, (Title) semanticObject); 
				return; 
			case BelegPackage.USE:
				sequence_Use(context, (Use) semanticObject); 
				return; 
			case BelegPackage.XPART:
				sequence_XPart(context, (XPart) semanticObject); 
				return; 
			case BelegPackage.YPART:
				sequence_YPart(context, (YPart) semanticObject); 
				return; 
			case BelegPackage.ZPART:
				sequence_ZPart(context, (ZPart) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Goal returns Goal
	 *
	 * Constraint:
	 *     (Ziel+=ID Ziel+=ID*)
	 * </pre>
	 */
	protected void sequence_Goal(ISerializationContext context, Goal semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     story+=S+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     S returns S
	 *
	 * Constraint:
	 *     (xe=XPart ye=YPart ze=ZPart)
	 * </pre>
	 */
	protected void sequence_S(ISerializationContext context, S semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.S__XE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.S__XE));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.S__YE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.S__YE));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.S__ZE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.S__ZE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSAccess().getXeXPartParserRuleCall_0_0(), semanticObject.getXe());
		feeder.accept(grammarAccess.getSAccess().getYeYPartParserRuleCall_1_0(), semanticObject.getYe());
		feeder.accept(grammarAccess.getSAccess().getZeZPartParserRuleCall_2_0(), semanticObject.getZe());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Story returns Story
	 *
	 * Constraint:
	 *     (
	 *         title+=ID 
	 *         title+=ID* 
	 *         use+=ID 
	 *         use+=ID* 
	 *         role=ID 
	 *         goal+=ID 
	 *         goal+=ID*
	 *     )
	 * </pre>
	 */
	protected void sequence_Story(ISerializationContext context, Story semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Title returns Title
	 *
	 * Constraint:
	 *     (Titel+=ID Titel+=ID*)
	 * </pre>
	 */
	protected void sequence_Title(ISerializationContext context, Title semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Use returns Use
	 *
	 * Constraint:
	 *     (Nutzen+=ID Nutzen+=ID*)
	 * </pre>
	 */
	protected void sequence_Use(ISerializationContext context, Use semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     XPart returns XPart
	 *
	 * Constraint:
	 *     ti=Title
	 * </pre>
	 */
	protected void sequence_XPart(ISerializationContext context, XPart semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.XPART__TI) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.XPART__TI));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXPartAccess().getTiTitleParserRuleCall_0_0(), semanticObject.getTi());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     YPart returns YPart
	 *
	 * Constraint:
	 *     us=Use
	 * </pre>
	 */
	protected void sequence_YPart(ISerializationContext context, YPart semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.YPART__US) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.YPART__US));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getYPartAccess().getUsUseParserRuleCall_0_0(), semanticObject.getUs());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ZPart returns ZPart
	 *
	 * Constraint:
	 *     (Rolle=ID go=Goal)
	 * </pre>
	 */
	protected void sequence_ZPart(ISerializationContext context, ZPart semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.ZPART__ROLLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.ZPART__ROLLE));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.ZPART__GO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.ZPART__GO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getZPartAccess().getRolleIDTerminalRuleCall_0_0(), semanticObject.getRolle());
		feeder.accept(grammarAccess.getZPartAccess().getGoGoalParserRuleCall_1_0(), semanticObject.getGo());
		feeder.finish();
	}
	
	
}
