/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.serializer;

import com.google.inject.Inject;
import de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Infinit;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Model;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Nutzen;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Rolle;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Substantiv;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Text;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Titel;
import de.htwdd.sf.beleg.s86320.s86372.beleg.User_Story_Um;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Ziel;
import de.htwdd.sf.beleg.s86320.s86372.services.BelegGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class BelegSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private BelegGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == BelegPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case BelegPackage.INFINIT:
				sequence_Infinit(context, (Infinit) semanticObject); 
				return; 
			case BelegPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case BelegPackage.NUTZEN:
				sequence_Nutzen(context, (Nutzen) semanticObject); 
				return; 
			case BelegPackage.ROLLE:
				sequence_Rolle(context, (Rolle) semanticObject); 
				return; 
			case BelegPackage.SUBSTANTIV:
				sequence_Substantiv(context, (Substantiv) semanticObject); 
				return; 
			case BelegPackage.TEXT:
				sequence_Text(context, (Text) semanticObject); 
				return; 
			case BelegPackage.TITEL:
				sequence_Titel(context, (Titel) semanticObject); 
				return; 
			case BelegPackage.USER_STORY_UM:
				sequence_User_Story_Um(context, (User_Story_Um) semanticObject); 
				return; 
			case BelegPackage.ZIEL:
				sequence_Ziel(context, (Ziel) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Infinit returns Infinit
	 *
	 * Constraint:
	 *     value=WORT
	 * </pre>
	 */
	protected void sequence_Infinit(ISerializationContext context, Infinit semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.INFINIT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.INFINIT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInfinitAccess().getValueWORTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     story+=User_Story_Um+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Nutzen returns Nutzen
	 *
	 * Constraint:
	 *     (subst=Substantiv zuBlock=ZuBlock? infinit+=Infinit+)
	 * </pre>
	 */
	protected void sequence_Nutzen(ISerializationContext context, Nutzen semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Rolle returns Rolle
	 *
	 * Constraint:
	 *     subst=Substantiv
	 * </pre>
	 */
	protected void sequence_Rolle(ISerializationContext context, Rolle semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.ROLLE__SUBST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.ROLLE__SUBST));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRolleAccess().getSubstSubstantivParserRuleCall_0(), semanticObject.getSubst());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Substantiv returns Substantiv
	 *
	 * Constraint:
	 *     value=WORT
	 * </pre>
	 */
	protected void sequence_Substantiv(ISerializationContext context, Substantiv semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.SUBSTANTIV__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.SUBSTANTIV__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSubstantivAccess().getValueWORTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Text returns Text
	 *
	 * Constraint:
	 *     value=WORT
	 * </pre>
	 */
	protected void sequence_Text(ISerializationContext context, Text semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.TEXT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.TEXT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTextAccess().getValueWORTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Titel returns Titel
	 *
	 * Constraint:
	 *     textpart+=Text+
	 * </pre>
	 */
	protected void sequence_Titel(ISerializationContext context, Titel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     User_Story_Um returns User_Story_Um
	 *
	 * Constraint:
	 *     (title=Titel use=Nutzen role=Rolle goal=Ziel)
	 * </pre>
	 */
	protected void sequence_User_Story_Um(ISerializationContext context, User_Story_Um semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__TITLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__TITLE));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__USE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__USE));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__ROLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__ROLE));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__GOAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__GOAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getTitleTitelParserRuleCall_0_0(), semanticObject.getTitle());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getUseNutzenParserRuleCall_3_0(), semanticObject.getUse());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getRoleRolleParserRuleCall_8_0(), semanticObject.getRole());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getGoalZielParserRuleCall_9_0(), semanticObject.getGoal());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Ziel returns Ziel
	 *
	 * Constraint:
	 *     (subst=Substantiv infinit+=Infinit+)
	 * </pre>
	 */
	protected void sequence_Ziel(ISerializationContext context, Ziel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
