/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.serializer;

import com.google.inject.Inject;
import de.htwdd.sf.beleg.s86320s86372.beleg.AlsBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage;
import de.htwdd.sf.beleg.s86320s86372.beleg.DoppelPunktBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.IchBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.Infinit;
import de.htwdd.sf.beleg.s86320s86372.beleg.KommaBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.Model;
import de.htwdd.sf.beleg.s86320s86372.beleg.MoechteBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen;
import de.htwdd.sf.beleg.s86320s86372.beleg.PunktBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.Rolle;
import de.htwdd.sf.beleg.s86320s86372.beleg.Substantiv;
import de.htwdd.sf.beleg.s86320s86372.beleg.Text;
import de.htwdd.sf.beleg.s86320s86372.beleg.Titel;
import de.htwdd.sf.beleg.s86320s86372.beleg.UmBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um;
import de.htwdd.sf.beleg.s86320s86372.beleg.Ziel;
import de.htwdd.sf.beleg.s86320s86372.beleg.ZuBlock;
import de.htwdd.sf.beleg.s86320s86372.services.BelegGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class BelegSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private BelegGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == BelegPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case BelegPackage.ALS_BLOCK:
				sequence_AlsBlock(context, (AlsBlock) semanticObject); 
				return; 
			case BelegPackage.DOPPEL_PUNKT_BLOCK:
				sequence_DoppelPunktBlock(context, (DoppelPunktBlock) semanticObject); 
				return; 
			case BelegPackage.ICH_BLOCK:
				sequence_IchBlock(context, (IchBlock) semanticObject); 
				return; 
			case BelegPackage.INFINIT:
				sequence_Infinit(context, (Infinit) semanticObject); 
				return; 
			case BelegPackage.KOMMA_BLOCK:
				sequence_KommaBlock(context, (KommaBlock) semanticObject); 
				return; 
			case BelegPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case BelegPackage.MOECHTE_BLOCK:
				sequence_MoechteBlock(context, (MoechteBlock) semanticObject); 
				return; 
			case BelegPackage.NUTZEN:
				sequence_Nutzen(context, (Nutzen) semanticObject); 
				return; 
			case BelegPackage.PUNKT_BLOCK:
				sequence_PunktBlock(context, (PunktBlock) semanticObject); 
				return; 
			case BelegPackage.ROLLE:
				sequence_Rolle(context, (Rolle) semanticObject); 
				return; 
			case BelegPackage.SUBSTANTIV:
				sequence_Substantiv(context, (Substantiv) semanticObject); 
				return; 
			case BelegPackage.TEXT:
				sequence_Text(context, (Text) semanticObject); 
				return; 
			case BelegPackage.TITEL:
				sequence_Titel(context, (Titel) semanticObject); 
				return; 
			case BelegPackage.UM_BLOCK:
				sequence_UmBlock(context, (UmBlock) semanticObject); 
				return; 
			case BelegPackage.USER_STORY_UM:
				sequence_User_Story_Um(context, (User_Story_Um) semanticObject); 
				return; 
			case BelegPackage.ZIEL:
				sequence_Ziel(context, (Ziel) semanticObject); 
				return; 
			case BelegPackage.ZU_BLOCK:
				sequence_ZuBlock(context, (ZuBlock) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     AlsBlock returns AlsBlock
	 *
	 * Constraint:
	 *     value='als'
	 * </pre>
	 */
	protected void sequence_AlsBlock(ISerializationContext context, AlsBlock semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.ALS_BLOCK__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.ALS_BLOCK__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAlsBlockAccess().getValueAlsKeyword_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     DoppelPunktBlock returns DoppelPunktBlock
	 *
	 * Constraint:
	 *     value=':'
	 * </pre>
	 */
	protected void sequence_DoppelPunktBlock(ISerializationContext context, DoppelPunktBlock semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.DOPPEL_PUNKT_BLOCK__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.DOPPEL_PUNKT_BLOCK__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDoppelPunktBlockAccess().getValueColonKeyword_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     IchBlock returns IchBlock
	 *
	 * Constraint:
	 *     value='ich'
	 * </pre>
	 */
	protected void sequence_IchBlock(ISerializationContext context, IchBlock semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.ICH_BLOCK__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.ICH_BLOCK__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIchBlockAccess().getValueIchKeyword_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Infinit returns Infinit
	 *
	 * Constraint:
	 *     value=WORT
	 * </pre>
	 */
	protected void sequence_Infinit(ISerializationContext context, Infinit semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.INFINIT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.INFINIT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInfinitAccess().getValueWORTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     KommaBlock returns KommaBlock
	 *
	 * Constraint:
	 *     value=','
	 * </pre>
	 */
	protected void sequence_KommaBlock(ISerializationContext context, KommaBlock semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.KOMMA_BLOCK__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.KOMMA_BLOCK__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getKommaBlockAccess().getValueCommaKeyword_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     story+=User_Story_Um+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MoechteBlock returns MoechteBlock
	 *
	 * Constraint:
	 *     value='möchte'
	 * </pre>
	 */
	protected void sequence_MoechteBlock(ISerializationContext context, MoechteBlock semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.MOECHTE_BLOCK__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.MOECHTE_BLOCK__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMoechteBlockAccess().getValueMöchteKeyword_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Nutzen returns Nutzen
	 *
	 * Constraint:
	 *     (subst=Substantiv zu=ZuBlock? infinit+=Infinit+)
	 * </pre>
	 */
	protected void sequence_Nutzen(ISerializationContext context, Nutzen semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PunktBlock returns PunktBlock
	 *
	 * Constraint:
	 *     value='.'
	 * </pre>
	 */
	protected void sequence_PunktBlock(ISerializationContext context, PunktBlock semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.PUNKT_BLOCK__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.PUNKT_BLOCK__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPunktBlockAccess().getValueFullStopKeyword_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Rolle returns Rolle
	 *
	 * Constraint:
	 *     subst=Substantiv
	 * </pre>
	 */
	protected void sequence_Rolle(ISerializationContext context, Rolle semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.ROLLE__SUBST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.ROLLE__SUBST));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRolleAccess().getSubstSubstantivParserRuleCall_0(), semanticObject.getSubst());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Substantiv returns Substantiv
	 *
	 * Constraint:
	 *     value=WORT
	 * </pre>
	 */
	protected void sequence_Substantiv(ISerializationContext context, Substantiv semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.SUBSTANTIV__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.SUBSTANTIV__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSubstantivAccess().getValueWORTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Text returns Text
	 *
	 * Constraint:
	 *     value=WORT
	 * </pre>
	 */
	protected void sequence_Text(ISerializationContext context, Text semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.TEXT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.TEXT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTextAccess().getValueWORTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Titel returns Titel
	 *
	 * Constraint:
	 *     textpart+=Text+
	 * </pre>
	 */
	protected void sequence_Titel(ISerializationContext context, Titel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UmBlock returns UmBlock
	 *
	 * Constraint:
	 *     value='Um'
	 * </pre>
	 */
	protected void sequence_UmBlock(ISerializationContext context, UmBlock semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.UM_BLOCK__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.UM_BLOCK__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUmBlockAccess().getValueUmKeyword_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     User_Story_Um returns User_Story_Um
	 *
	 * Constraint:
	 *     (
	 *         title=Titel 
	 *         doppelpunkt=DoppelPunktBlock 
	 *         um=UmBlock 
	 *         use=Nutzen 
	 *         komma=KommaBlock 
	 *         moechte=MoechteBlock 
	 *         ich=IchBlock 
	 *         als=AlsBlock 
	 *         role=Rolle 
	 *         goal=Ziel 
	 *         punkt=PunktBlock
	 *     )
	 * </pre>
	 */
	protected void sequence_User_Story_Um(ISerializationContext context, User_Story_Um semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__TITLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__TITLE));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__DOPPELPUNKT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__DOPPELPUNKT));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__UM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__UM));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__USE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__USE));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__KOMMA) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__KOMMA));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__MOECHTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__MOECHTE));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__ICH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__ICH));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__ALS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__ALS));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__ROLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__ROLE));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__GOAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__GOAL));
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.USER_STORY_UM__PUNKT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.USER_STORY_UM__PUNKT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getTitleTitelParserRuleCall_0_0(), semanticObject.getTitle());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getDoppelpunktDoppelPunktBlockParserRuleCall_1_0(), semanticObject.getDoppelpunkt());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getUmUmBlockParserRuleCall_2_0(), semanticObject.getUm());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getUseNutzenParserRuleCall_3_0(), semanticObject.getUse());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getKommaKommaBlockParserRuleCall_4_0(), semanticObject.getKomma());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getMoechteMoechteBlockParserRuleCall_5_0(), semanticObject.getMoechte());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getIchIchBlockParserRuleCall_6_0(), semanticObject.getIch());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getAlsAlsBlockParserRuleCall_7_0(), semanticObject.getAls());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getRoleRolleParserRuleCall_8_0(), semanticObject.getRole());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getGoalZielParserRuleCall_9_0(), semanticObject.getGoal());
		feeder.accept(grammarAccess.getUser_Story_UmAccess().getPunktPunktBlockParserRuleCall_10_0(), semanticObject.getPunkt());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Ziel returns Ziel
	 *
	 * Constraint:
	 *     (subst=Substantiv infinit+=Infinit+)
	 * </pre>
	 */
	protected void sequence_Ziel(ISerializationContext context, Ziel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ZuBlock returns ZuBlock
	 *
	 * Constraint:
	 *     value='zu'
	 * </pre>
	 */
	protected void sequence_ZuBlock(ISerializationContext context, ZuBlock semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BelegPackage.Literals.ZU_BLOCK__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BelegPackage.Literals.ZU_BLOCK__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getZuBlockAccess().getValueZuKeyword_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
}
