/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.beleg.impl;

import de.htwdd.sf.beleg.s86320s86372.beleg.AlsBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.BelegFactory;
import de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage;
import de.htwdd.sf.beleg.s86320s86372.beleg.DoppelPunktBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.IchBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.Infinit;
import de.htwdd.sf.beleg.s86320s86372.beleg.KommaBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.Model;
import de.htwdd.sf.beleg.s86320s86372.beleg.MoechteBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen;
import de.htwdd.sf.beleg.s86320s86372.beleg.PunktBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.Rolle;
import de.htwdd.sf.beleg.s86320s86372.beleg.Substantiv;
import de.htwdd.sf.beleg.s86320s86372.beleg.Text;
import de.htwdd.sf.beleg.s86320s86372.beleg.Titel;
import de.htwdd.sf.beleg.s86320s86372.beleg.UmBlock;
import de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um;
import de.htwdd.sf.beleg.s86320s86372.beleg.Ziel;
import de.htwdd.sf.beleg.s86320s86372.beleg.ZuBlock;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BelegPackageImpl extends EPackageImpl implements BelegPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass user_Story_UmEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass titelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass textEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nutzenEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rolleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass zielEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass doppelPunktBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass umBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass kommaBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass zuBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moechteBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ichBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass alsBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass punktBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass substantivEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass infinitEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private BelegPackageImpl()
  {
    super(eNS_URI, BelegFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link BelegPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static BelegPackage init()
  {
    if (isInited) return (BelegPackage)EPackage.Registry.INSTANCE.getEPackage(BelegPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredBelegPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    BelegPackageImpl theBelegPackage = registeredBelegPackage instanceof BelegPackageImpl ? (BelegPackageImpl)registeredBelegPackage : new BelegPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theBelegPackage.createPackageContents();

    // Initialize created meta-data
    theBelegPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theBelegPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(BelegPackage.eNS_URI, theBelegPackage);
    return theBelegPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Story()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUser_Story_Um()
  {
    return user_Story_UmEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Title()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Doppelpunkt()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Um()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Use()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Komma()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Moechte()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Ich()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Als()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Role()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Goal()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUser_Story_Um_Punkt()
  {
    return (EReference)user_Story_UmEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTitel()
  {
    return titelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTitel_Textpart()
  {
    return (EReference)titelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getText()
  {
    return textEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getText_Value()
  {
    return (EAttribute)textEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNutzen()
  {
    return nutzenEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNutzen_Subst()
  {
    return (EReference)nutzenEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNutzen_Zu()
  {
    return (EReference)nutzenEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNutzen_Infinit()
  {
    return (EReference)nutzenEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRolle()
  {
    return rolleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRolle_Subst()
  {
    return (EReference)rolleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getZiel()
  {
    return zielEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getZiel_Subst()
  {
    return (EReference)zielEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getZiel_Infinit()
  {
    return (EReference)zielEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDoppelPunktBlock()
  {
    return doppelPunktBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDoppelPunktBlock_Value()
  {
    return (EAttribute)doppelPunktBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUmBlock()
  {
    return umBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUmBlock_Value()
  {
    return (EAttribute)umBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getKommaBlock()
  {
    return kommaBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getKommaBlock_Value()
  {
    return (EAttribute)kommaBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getZuBlock()
  {
    return zuBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getZuBlock_Value()
  {
    return (EAttribute)zuBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMoechteBlock()
  {
    return moechteBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMoechteBlock_Value()
  {
    return (EAttribute)moechteBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIchBlock()
  {
    return ichBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIchBlock_Value()
  {
    return (EAttribute)ichBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAlsBlock()
  {
    return alsBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlsBlock_Value()
  {
    return (EAttribute)alsBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPunktBlock()
  {
    return punktBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPunktBlock_Value()
  {
    return (EAttribute)punktBlockEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSubstantiv()
  {
    return substantivEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSubstantiv_Value()
  {
    return (EAttribute)substantivEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInfinit()
  {
    return infinitEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInfinit_Value()
  {
    return (EAttribute)infinitEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BelegFactory getBelegFactory()
  {
    return (BelegFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__STORY);

    user_Story_UmEClass = createEClass(USER_STORY_UM);
    createEReference(user_Story_UmEClass, USER_STORY_UM__TITLE);
    createEReference(user_Story_UmEClass, USER_STORY_UM__DOPPELPUNKT);
    createEReference(user_Story_UmEClass, USER_STORY_UM__UM);
    createEReference(user_Story_UmEClass, USER_STORY_UM__USE);
    createEReference(user_Story_UmEClass, USER_STORY_UM__KOMMA);
    createEReference(user_Story_UmEClass, USER_STORY_UM__MOECHTE);
    createEReference(user_Story_UmEClass, USER_STORY_UM__ICH);
    createEReference(user_Story_UmEClass, USER_STORY_UM__ALS);
    createEReference(user_Story_UmEClass, USER_STORY_UM__ROLE);
    createEReference(user_Story_UmEClass, USER_STORY_UM__GOAL);
    createEReference(user_Story_UmEClass, USER_STORY_UM__PUNKT);

    titelEClass = createEClass(TITEL);
    createEReference(titelEClass, TITEL__TEXTPART);

    textEClass = createEClass(TEXT);
    createEAttribute(textEClass, TEXT__VALUE);

    nutzenEClass = createEClass(NUTZEN);
    createEReference(nutzenEClass, NUTZEN__SUBST);
    createEReference(nutzenEClass, NUTZEN__ZU);
    createEReference(nutzenEClass, NUTZEN__INFINIT);

    rolleEClass = createEClass(ROLLE);
    createEReference(rolleEClass, ROLLE__SUBST);

    zielEClass = createEClass(ZIEL);
    createEReference(zielEClass, ZIEL__SUBST);
    createEReference(zielEClass, ZIEL__INFINIT);

    doppelPunktBlockEClass = createEClass(DOPPEL_PUNKT_BLOCK);
    createEAttribute(doppelPunktBlockEClass, DOPPEL_PUNKT_BLOCK__VALUE);

    umBlockEClass = createEClass(UM_BLOCK);
    createEAttribute(umBlockEClass, UM_BLOCK__VALUE);

    kommaBlockEClass = createEClass(KOMMA_BLOCK);
    createEAttribute(kommaBlockEClass, KOMMA_BLOCK__VALUE);

    zuBlockEClass = createEClass(ZU_BLOCK);
    createEAttribute(zuBlockEClass, ZU_BLOCK__VALUE);

    moechteBlockEClass = createEClass(MOECHTE_BLOCK);
    createEAttribute(moechteBlockEClass, MOECHTE_BLOCK__VALUE);

    ichBlockEClass = createEClass(ICH_BLOCK);
    createEAttribute(ichBlockEClass, ICH_BLOCK__VALUE);

    alsBlockEClass = createEClass(ALS_BLOCK);
    createEAttribute(alsBlockEClass, ALS_BLOCK__VALUE);

    punktBlockEClass = createEClass(PUNKT_BLOCK);
    createEAttribute(punktBlockEClass, PUNKT_BLOCK__VALUE);

    substantivEClass = createEClass(SUBSTANTIV);
    createEAttribute(substantivEClass, SUBSTANTIV__VALUE);

    infinitEClass = createEClass(INFINIT);
    createEAttribute(infinitEClass, INFINIT__VALUE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Story(), this.getUser_Story_Um(), null, "story", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(user_Story_UmEClass, User_Story_Um.class, "User_Story_Um", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUser_Story_Um_Title(), this.getTitel(), null, "title", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUser_Story_Um_Doppelpunkt(), this.getDoppelPunktBlock(), null, "doppelpunkt", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUser_Story_Um_Um(), this.getUmBlock(), null, "um", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUser_Story_Um_Use(), this.getNutzen(), null, "use", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUser_Story_Um_Komma(), this.getKommaBlock(), null, "komma", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUser_Story_Um_Moechte(), this.getMoechteBlock(), null, "moechte", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUser_Story_Um_Ich(), this.getIchBlock(), null, "ich", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUser_Story_Um_Als(), this.getAlsBlock(), null, "als", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUser_Story_Um_Role(), this.getRolle(), null, "role", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUser_Story_Um_Goal(), this.getZiel(), null, "goal", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUser_Story_Um_Punkt(), this.getPunktBlock(), null, "punkt", null, 0, 1, User_Story_Um.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(titelEClass, Titel.class, "Titel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTitel_Textpart(), this.getText(), null, "textpart", null, 0, -1, Titel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(textEClass, Text.class, "Text", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getText_Value(), ecorePackage.getEString(), "value", null, 0, 1, Text.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(nutzenEClass, Nutzen.class, "Nutzen", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getNutzen_Subst(), this.getSubstantiv(), null, "subst", null, 0, 1, Nutzen.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNutzen_Zu(), this.getZuBlock(), null, "zu", null, 0, 1, Nutzen.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNutzen_Infinit(), this.getInfinit(), null, "infinit", null, 0, -1, Nutzen.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rolleEClass, Rolle.class, "Rolle", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRolle_Subst(), this.getSubstantiv(), null, "subst", null, 0, 1, Rolle.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(zielEClass, Ziel.class, "Ziel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getZiel_Subst(), this.getSubstantiv(), null, "subst", null, 0, 1, Ziel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getZiel_Infinit(), this.getInfinit(), null, "infinit", null, 0, -1, Ziel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(doppelPunktBlockEClass, DoppelPunktBlock.class, "DoppelPunktBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDoppelPunktBlock_Value(), ecorePackage.getEString(), "value", null, 0, 1, DoppelPunktBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(umBlockEClass, UmBlock.class, "UmBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUmBlock_Value(), ecorePackage.getEString(), "value", null, 0, 1, UmBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(kommaBlockEClass, KommaBlock.class, "KommaBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getKommaBlock_Value(), ecorePackage.getEString(), "value", null, 0, 1, KommaBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(zuBlockEClass, ZuBlock.class, "ZuBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getZuBlock_Value(), ecorePackage.getEString(), "value", null, 0, 1, ZuBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(moechteBlockEClass, MoechteBlock.class, "MoechteBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMoechteBlock_Value(), ecorePackage.getEString(), "value", null, 0, 1, MoechteBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ichBlockEClass, IchBlock.class, "IchBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIchBlock_Value(), ecorePackage.getEString(), "value", null, 0, 1, IchBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(alsBlockEClass, AlsBlock.class, "AlsBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAlsBlock_Value(), ecorePackage.getEString(), "value", null, 0, 1, AlsBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(punktBlockEClass, PunktBlock.class, "PunktBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPunktBlock_Value(), ecorePackage.getEString(), "value", null, 0, 1, PunktBlock.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(substantivEClass, Substantiv.class, "Substantiv", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSubstantiv_Value(), ecorePackage.getEString(), "value", null, 0, 1, Substantiv.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(infinitEClass, Infinit.class, "Infinit", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInfinit_Value(), ecorePackage.getEString(), "value", null, 0, 1, Infinit.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //BelegPackageImpl
