/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.beleg.impl;

import de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage;
import de.htwdd.sf.beleg.s86320s86372.beleg.Infinit;
import de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen;
import de.htwdd.sf.beleg.s86320s86372.beleg.Substantiv;
import de.htwdd.sf.beleg.s86320s86372.beleg.ZuBlock;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Nutzen</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.NutzenImpl#getSubst <em>Subst</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.NutzenImpl#getZu <em>Zu</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.NutzenImpl#getInfinit <em>Infinit</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NutzenImpl extends MinimalEObjectImpl.Container implements Nutzen
{
  /**
   * The cached value of the '{@link #getSubst() <em>Subst</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubst()
   * @generated
   * @ordered
   */
  protected Substantiv subst;

  /**
   * The cached value of the '{@link #getZu() <em>Zu</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZu()
   * @generated
   * @ordered
   */
  protected ZuBlock zu;

  /**
   * The cached value of the '{@link #getInfinit() <em>Infinit</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInfinit()
   * @generated
   * @ordered
   */
  protected EList<Infinit> infinit;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NutzenImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BelegPackage.Literals.NUTZEN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Substantiv getSubst()
  {
    return subst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSubst(Substantiv newSubst, NotificationChain msgs)
  {
    Substantiv oldSubst = subst;
    subst = newSubst;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BelegPackage.NUTZEN__SUBST, oldSubst, newSubst);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubst(Substantiv newSubst)
  {
    if (newSubst != subst)
    {
      NotificationChain msgs = null;
      if (subst != null)
        msgs = ((InternalEObject)subst).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BelegPackage.NUTZEN__SUBST, null, msgs);
      if (newSubst != null)
        msgs = ((InternalEObject)newSubst).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BelegPackage.NUTZEN__SUBST, null, msgs);
      msgs = basicSetSubst(newSubst, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BelegPackage.NUTZEN__SUBST, newSubst, newSubst));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ZuBlock getZu()
  {
    return zu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetZu(ZuBlock newZu, NotificationChain msgs)
  {
    ZuBlock oldZu = zu;
    zu = newZu;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BelegPackage.NUTZEN__ZU, oldZu, newZu);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setZu(ZuBlock newZu)
  {
    if (newZu != zu)
    {
      NotificationChain msgs = null;
      if (zu != null)
        msgs = ((InternalEObject)zu).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BelegPackage.NUTZEN__ZU, null, msgs);
      if (newZu != null)
        msgs = ((InternalEObject)newZu).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BelegPackage.NUTZEN__ZU, null, msgs);
      msgs = basicSetZu(newZu, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BelegPackage.NUTZEN__ZU, newZu, newZu));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Infinit> getInfinit()
  {
    if (infinit == null)
    {
      infinit = new EObjectContainmentEList<Infinit>(Infinit.class, this, BelegPackage.NUTZEN__INFINIT);
    }
    return infinit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BelegPackage.NUTZEN__SUBST:
        return basicSetSubst(null, msgs);
      case BelegPackage.NUTZEN__ZU:
        return basicSetZu(null, msgs);
      case BelegPackage.NUTZEN__INFINIT:
        return ((InternalEList<?>)getInfinit()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BelegPackage.NUTZEN__SUBST:
        return getSubst();
      case BelegPackage.NUTZEN__ZU:
        return getZu();
      case BelegPackage.NUTZEN__INFINIT:
        return getInfinit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BelegPackage.NUTZEN__SUBST:
        setSubst((Substantiv)newValue);
        return;
      case BelegPackage.NUTZEN__ZU:
        setZu((ZuBlock)newValue);
        return;
      case BelegPackage.NUTZEN__INFINIT:
        getInfinit().clear();
        getInfinit().addAll((Collection<? extends Infinit>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BelegPackage.NUTZEN__SUBST:
        setSubst((Substantiv)null);
        return;
      case BelegPackage.NUTZEN__ZU:
        setZu((ZuBlock)null);
        return;
      case BelegPackage.NUTZEN__INFINIT:
        getInfinit().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BelegPackage.NUTZEN__SUBST:
        return subst != null;
      case BelegPackage.NUTZEN__ZU:
        return zu != null;
      case BelegPackage.NUTZEN__INFINIT:
        return infinit != null && !infinit.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //NutzenImpl
