/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.beleg.impl;

import de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage;
import de.htwdd.sf.beleg.s86320s86372.beleg.Rolle;
import de.htwdd.sf.beleg.s86320s86372.beleg.Substantiv;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rolle</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.RolleImpl#getSubst <em>Subst</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RolleImpl extends MinimalEObjectImpl.Container implements Rolle
{
  /**
   * The cached value of the '{@link #getSubst() <em>Subst</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubst()
   * @generated
   * @ordered
   */
  protected Substantiv subst;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RolleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BelegPackage.Literals.ROLLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Substantiv getSubst()
  {
    return subst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSubst(Substantiv newSubst, NotificationChain msgs)
  {
    Substantiv oldSubst = subst;
    subst = newSubst;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BelegPackage.ROLLE__SUBST, oldSubst, newSubst);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubst(Substantiv newSubst)
  {
    if (newSubst != subst)
    {
      NotificationChain msgs = null;
      if (subst != null)
        msgs = ((InternalEObject)subst).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BelegPackage.ROLLE__SUBST, null, msgs);
      if (newSubst != null)
        msgs = ((InternalEObject)newSubst).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BelegPackage.ROLLE__SUBST, null, msgs);
      msgs = basicSetSubst(newSubst, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BelegPackage.ROLLE__SUBST, newSubst, newSubst));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BelegPackage.ROLLE__SUBST:
        return basicSetSubst(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BelegPackage.ROLLE__SUBST:
        return getSubst();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BelegPackage.ROLLE__SUBST:
        setSubst((Substantiv)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BelegPackage.ROLLE__SUBST:
        setSubst((Substantiv)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BelegPackage.ROLLE__SUBST:
        return subst != null;
    }
    return super.eIsSet(featureID);
  }

} //RolleImpl
