/*
 * generated by Xtext 2.41.0
 */
grammar InternalBeleg;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package de.htwdd.sf.beleg.s86320s86372.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package de.htwdd.sf.beleg.s86320s86372.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import de.htwdd.sf.beleg.s86320s86372.services.BelegGrammarAccess;

}
@parser::members {
	private BelegGrammarAccess grammarAccess;

	public void setGrammarAccess(BelegGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleModel
entryRuleModel
:
{ before(grammarAccess.getModelRule()); }
	 ruleModel
{ after(grammarAccess.getModelRule()); } 
	 EOF 
;

// Rule Model
ruleModel 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		(
			{ before(grammarAccess.getModelAccess().getStoryAssignment()); }
			(rule__Model__StoryAssignment)
			{ after(grammarAccess.getModelAccess().getStoryAssignment()); }
		)
		(
			{ before(grammarAccess.getModelAccess().getStoryAssignment()); }
			(rule__Model__StoryAssignment)*
			{ after(grammarAccess.getModelAccess().getStoryAssignment()); }
		)
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleUser_Story_Um
entryRuleUser_Story_Um
:
{ before(grammarAccess.getUser_Story_UmRule()); }
	 ruleUser_Story_Um
{ after(grammarAccess.getUser_Story_UmRule()); } 
	 EOF 
;

// Rule User_Story_Um
ruleUser_Story_Um 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getGroup()); }
		(rule__User_Story_Um__Group__0)
		{ after(grammarAccess.getUser_Story_UmAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleTitel
entryRuleTitel
:
{ before(grammarAccess.getTitelRule()); }
	 ruleTitel
{ after(grammarAccess.getTitelRule()); } 
	 EOF 
;

// Rule Titel
ruleTitel 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		(
			{ before(grammarAccess.getTitelAccess().getTextpartAssignment()); }
			(rule__Titel__TextpartAssignment)
			{ after(grammarAccess.getTitelAccess().getTextpartAssignment()); }
		)
		(
			{ before(grammarAccess.getTitelAccess().getTextpartAssignment()); }
			(rule__Titel__TextpartAssignment)*
			{ after(grammarAccess.getTitelAccess().getTextpartAssignment()); }
		)
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleText
entryRuleText
:
{ before(grammarAccess.getTextRule()); }
	 ruleText
{ after(grammarAccess.getTextRule()); } 
	 EOF 
;

// Rule Text
ruleText 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getTextAccess().getValueAssignment()); }
		(rule__Text__ValueAssignment)
		{ after(grammarAccess.getTextAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleNutzen
entryRuleNutzen
:
{ before(grammarAccess.getNutzenRule()); }
	 ruleNutzen
{ after(grammarAccess.getNutzenRule()); } 
	 EOF 
;

// Rule Nutzen
ruleNutzen 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getNutzenAccess().getGroup()); }
		(rule__Nutzen__Group__0)
		{ after(grammarAccess.getNutzenAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleRolle
entryRuleRolle
:
{ before(grammarAccess.getRolleRule()); }
	 ruleRolle
{ after(grammarAccess.getRolleRule()); } 
	 EOF 
;

// Rule Rolle
ruleRolle 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getRolleAccess().getSubstAssignment()); }
		(rule__Rolle__SubstAssignment)
		{ after(grammarAccess.getRolleAccess().getSubstAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleZiel
entryRuleZiel
:
{ before(grammarAccess.getZielRule()); }
	 ruleZiel
{ after(grammarAccess.getZielRule()); } 
	 EOF 
;

// Rule Ziel
ruleZiel 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getZielAccess().getGroup()); }
		(rule__Ziel__Group__0)
		{ after(grammarAccess.getZielAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleDoppelPunktBlock
entryRuleDoppelPunktBlock
:
{ before(grammarAccess.getDoppelPunktBlockRule()); }
	 ruleDoppelPunktBlock
{ after(grammarAccess.getDoppelPunktBlockRule()); } 
	 EOF 
;

// Rule DoppelPunktBlock
ruleDoppelPunktBlock 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getDoppelPunktBlockAccess().getValueAssignment()); }
		(rule__DoppelPunktBlock__ValueAssignment)
		{ after(grammarAccess.getDoppelPunktBlockAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleUmBlock
entryRuleUmBlock
:
{ before(grammarAccess.getUmBlockRule()); }
	 ruleUmBlock
{ after(grammarAccess.getUmBlockRule()); } 
	 EOF 
;

// Rule UmBlock
ruleUmBlock 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getUmBlockAccess().getValueAssignment()); }
		(rule__UmBlock__ValueAssignment)
		{ after(grammarAccess.getUmBlockAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleKommaBlock
entryRuleKommaBlock
:
{ before(grammarAccess.getKommaBlockRule()); }
	 ruleKommaBlock
{ after(grammarAccess.getKommaBlockRule()); } 
	 EOF 
;

// Rule KommaBlock
ruleKommaBlock 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getKommaBlockAccess().getValueAssignment()); }
		(rule__KommaBlock__ValueAssignment)
		{ after(grammarAccess.getKommaBlockAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleZuBlock
entryRuleZuBlock
:
{ before(grammarAccess.getZuBlockRule()); }
	 ruleZuBlock
{ after(grammarAccess.getZuBlockRule()); } 
	 EOF 
;

// Rule ZuBlock
ruleZuBlock 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getZuBlockAccess().getValueAssignment()); }
		(rule__ZuBlock__ValueAssignment)
		{ after(grammarAccess.getZuBlockAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMoechteBlock
entryRuleMoechteBlock
:
{ before(grammarAccess.getMoechteBlockRule()); }
	 ruleMoechteBlock
{ after(grammarAccess.getMoechteBlockRule()); } 
	 EOF 
;

// Rule MoechteBlock
ruleMoechteBlock 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMoechteBlockAccess().getValueAssignment()); }
		(rule__MoechteBlock__ValueAssignment)
		{ after(grammarAccess.getMoechteBlockAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleIchBlock
entryRuleIchBlock
:
{ before(grammarAccess.getIchBlockRule()); }
	 ruleIchBlock
{ after(grammarAccess.getIchBlockRule()); } 
	 EOF 
;

// Rule IchBlock
ruleIchBlock 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getIchBlockAccess().getValueAssignment()); }
		(rule__IchBlock__ValueAssignment)
		{ after(grammarAccess.getIchBlockAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAlsBlock
entryRuleAlsBlock
:
{ before(grammarAccess.getAlsBlockRule()); }
	 ruleAlsBlock
{ after(grammarAccess.getAlsBlockRule()); } 
	 EOF 
;

// Rule AlsBlock
ruleAlsBlock 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAlsBlockAccess().getValueAssignment()); }
		(rule__AlsBlock__ValueAssignment)
		{ after(grammarAccess.getAlsBlockAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRulePunktBlock
entryRulePunktBlock
:
{ before(grammarAccess.getPunktBlockRule()); }
	 rulePunktBlock
{ after(grammarAccess.getPunktBlockRule()); } 
	 EOF 
;

// Rule PunktBlock
rulePunktBlock 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getPunktBlockAccess().getValueAssignment()); }
		(rule__PunktBlock__ValueAssignment)
		{ after(grammarAccess.getPunktBlockAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleSubstantiv
entryRuleSubstantiv
:
{ before(grammarAccess.getSubstantivRule()); }
	 ruleSubstantiv
{ after(grammarAccess.getSubstantivRule()); } 
	 EOF 
;

// Rule Substantiv
ruleSubstantiv 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getSubstantivAccess().getValueAssignment()); }
		(rule__Substantiv__ValueAssignment)
		{ after(grammarAccess.getSubstantivAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleInfinit
entryRuleInfinit
:
{ before(grammarAccess.getInfinitRule()); }
	 ruleInfinit
{ after(grammarAccess.getInfinitRule()); } 
	 EOF 
;

// Rule Infinit
ruleInfinit 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getInfinitAccess().getValueAssignment()); }
		(rule__Infinit__ValueAssignment)
		{ after(grammarAccess.getInfinitAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__0__Impl
	rule__User_Story_Um__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getTitleAssignment_0()); }
	(rule__User_Story_Um__TitleAssignment_0)
	{ after(grammarAccess.getUser_Story_UmAccess().getTitleAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__1__Impl
	rule__User_Story_Um__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getDoppelpunktAssignment_1()); }
	(rule__User_Story_Um__DoppelpunktAssignment_1)
	{ after(grammarAccess.getUser_Story_UmAccess().getDoppelpunktAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__2__Impl
	rule__User_Story_Um__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getUmAssignment_2()); }
	(rule__User_Story_Um__UmAssignment_2)
	{ after(grammarAccess.getUser_Story_UmAccess().getUmAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__3__Impl
	rule__User_Story_Um__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getUseAssignment_3()); }
	(rule__User_Story_Um__UseAssignment_3)
	{ after(grammarAccess.getUser_Story_UmAccess().getUseAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__4__Impl
	rule__User_Story_Um__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getKommaAssignment_4()); }
	(rule__User_Story_Um__KommaAssignment_4)
	{ after(grammarAccess.getUser_Story_UmAccess().getKommaAssignment_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__5__Impl
	rule__User_Story_Um__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getMoechteAssignment_5()); }
	(rule__User_Story_Um__MoechteAssignment_5)
	{ after(grammarAccess.getUser_Story_UmAccess().getMoechteAssignment_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__6__Impl
	rule__User_Story_Um__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getIchAssignment_6()); }
	(rule__User_Story_Um__IchAssignment_6)
	{ after(grammarAccess.getUser_Story_UmAccess().getIchAssignment_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__7__Impl
	rule__User_Story_Um__Group__8
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getAlsAssignment_7()); }
	(rule__User_Story_Um__AlsAssignment_7)
	{ after(grammarAccess.getUser_Story_UmAccess().getAlsAssignment_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__8
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__8__Impl
	rule__User_Story_Um__Group__9
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__8__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getRoleAssignment_8()); }
	(rule__User_Story_Um__RoleAssignment_8)
	{ after(grammarAccess.getUser_Story_UmAccess().getRoleAssignment_8()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__9
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__9__Impl
	rule__User_Story_Um__Group__10
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__9__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getGoalAssignment_9()); }
	(rule__User_Story_Um__GoalAssignment_9)
	{ after(grammarAccess.getUser_Story_UmAccess().getGoalAssignment_9()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__10
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__User_Story_Um__Group__10__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__Group__10__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUser_Story_UmAccess().getPunktAssignment_10()); }
	(rule__User_Story_Um__PunktAssignment_10)
	{ after(grammarAccess.getUser_Story_UmAccess().getPunktAssignment_10()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Nutzen__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Nutzen__Group__0__Impl
	rule__Nutzen__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Nutzen__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNutzenAccess().getSubstAssignment_0()); }
	(rule__Nutzen__SubstAssignment_0)
	{ after(grammarAccess.getNutzenAccess().getSubstAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Nutzen__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Nutzen__Group__1__Impl
	rule__Nutzen__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Nutzen__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNutzenAccess().getZuAssignment_1()); }
	(rule__Nutzen__ZuAssignment_1)?
	{ after(grammarAccess.getNutzenAccess().getZuAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Nutzen__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Nutzen__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Nutzen__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getNutzenAccess().getInfinitAssignment_2()); }
		(rule__Nutzen__InfinitAssignment_2)
		{ after(grammarAccess.getNutzenAccess().getInfinitAssignment_2()); }
	)
	(
		{ before(grammarAccess.getNutzenAccess().getInfinitAssignment_2()); }
		(rule__Nutzen__InfinitAssignment_2)*
		{ after(grammarAccess.getNutzenAccess().getInfinitAssignment_2()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Ziel__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Ziel__Group__0__Impl
	rule__Ziel__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Ziel__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getZielAccess().getSubstAssignment_0()); }
	(rule__Ziel__SubstAssignment_0)
	{ after(grammarAccess.getZielAccess().getSubstAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Ziel__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Ziel__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Ziel__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getZielAccess().getInfinitAssignment_1()); }
		(rule__Ziel__InfinitAssignment_1)
		{ after(grammarAccess.getZielAccess().getInfinitAssignment_1()); }
	)
	(
		{ before(grammarAccess.getZielAccess().getInfinitAssignment_1()); }
		(rule__Ziel__InfinitAssignment_1)*
		{ after(grammarAccess.getZielAccess().getInfinitAssignment_1()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Model__StoryAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getModelAccess().getStoryUser_Story_UmParserRuleCall_0()); }
		ruleUser_Story_Um
		{ after(grammarAccess.getModelAccess().getStoryUser_Story_UmParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__TitleAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getTitleTitelParserRuleCall_0_0()); }
		ruleTitel
		{ after(grammarAccess.getUser_Story_UmAccess().getTitleTitelParserRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__DoppelpunktAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getDoppelpunktDoppelPunktBlockParserRuleCall_1_0()); }
		ruleDoppelPunktBlock
		{ after(grammarAccess.getUser_Story_UmAccess().getDoppelpunktDoppelPunktBlockParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__UmAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getUmUmBlockParserRuleCall_2_0()); }
		ruleUmBlock
		{ after(grammarAccess.getUser_Story_UmAccess().getUmUmBlockParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__UseAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getUseNutzenParserRuleCall_3_0()); }
		ruleNutzen
		{ after(grammarAccess.getUser_Story_UmAccess().getUseNutzenParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__KommaAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getKommaKommaBlockParserRuleCall_4_0()); }
		ruleKommaBlock
		{ after(grammarAccess.getUser_Story_UmAccess().getKommaKommaBlockParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__MoechteAssignment_5
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getMoechteMoechteBlockParserRuleCall_5_0()); }
		ruleMoechteBlock
		{ after(grammarAccess.getUser_Story_UmAccess().getMoechteMoechteBlockParserRuleCall_5_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__IchAssignment_6
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getIchIchBlockParserRuleCall_6_0()); }
		ruleIchBlock
		{ after(grammarAccess.getUser_Story_UmAccess().getIchIchBlockParserRuleCall_6_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__AlsAssignment_7
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getAlsAlsBlockParserRuleCall_7_0()); }
		ruleAlsBlock
		{ after(grammarAccess.getUser_Story_UmAccess().getAlsAlsBlockParserRuleCall_7_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__RoleAssignment_8
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getRoleRolleParserRuleCall_8_0()); }
		ruleRolle
		{ after(grammarAccess.getUser_Story_UmAccess().getRoleRolleParserRuleCall_8_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__GoalAssignment_9
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getGoalZielParserRuleCall_9_0()); }
		ruleZiel
		{ after(grammarAccess.getUser_Story_UmAccess().getGoalZielParserRuleCall_9_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__User_Story_Um__PunktAssignment_10
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUser_Story_UmAccess().getPunktPunktBlockParserRuleCall_10_0()); }
		rulePunktBlock
		{ after(grammarAccess.getUser_Story_UmAccess().getPunktPunktBlockParserRuleCall_10_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Titel__TextpartAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTitelAccess().getTextpartTextParserRuleCall_0()); }
		ruleText
		{ after(grammarAccess.getTitelAccess().getTextpartTextParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Text__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTextAccess().getValueWORTTerminalRuleCall_0()); }
		RULE_WORT
		{ after(grammarAccess.getTextAccess().getValueWORTTerminalRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Nutzen__SubstAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getNutzenAccess().getSubstSubstantivParserRuleCall_0_0()); }
		ruleSubstantiv
		{ after(grammarAccess.getNutzenAccess().getSubstSubstantivParserRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Nutzen__ZuAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getNutzenAccess().getZuZuBlockParserRuleCall_1_0()); }
		ruleZuBlock
		{ after(grammarAccess.getNutzenAccess().getZuZuBlockParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Nutzen__InfinitAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getNutzenAccess().getInfinitInfinitParserRuleCall_2_0()); }
		ruleInfinit
		{ after(grammarAccess.getNutzenAccess().getInfinitInfinitParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Rolle__SubstAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRolleAccess().getSubstSubstantivParserRuleCall_0()); }
		ruleSubstantiv
		{ after(grammarAccess.getRolleAccess().getSubstSubstantivParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Ziel__SubstAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getZielAccess().getSubstSubstantivParserRuleCall_0_0()); }
		ruleSubstantiv
		{ after(grammarAccess.getZielAccess().getSubstSubstantivParserRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Ziel__InfinitAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getZielAccess().getInfinitInfinitParserRuleCall_1_0()); }
		ruleInfinit
		{ after(grammarAccess.getZielAccess().getInfinitInfinitParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__DoppelPunktBlock__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDoppelPunktBlockAccess().getValueColonKeyword_0()); }
		(
			{ before(grammarAccess.getDoppelPunktBlockAccess().getValueColonKeyword_0()); }
			':'
			{ after(grammarAccess.getDoppelPunktBlockAccess().getValueColonKeyword_0()); }
		)
		{ after(grammarAccess.getDoppelPunktBlockAccess().getValueColonKeyword_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__UmBlock__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUmBlockAccess().getValueUmKeyword_0()); }
		(
			{ before(grammarAccess.getUmBlockAccess().getValueUmKeyword_0()); }
			'Um'
			{ after(grammarAccess.getUmBlockAccess().getValueUmKeyword_0()); }
		)
		{ after(grammarAccess.getUmBlockAccess().getValueUmKeyword_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__KommaBlock__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getKommaBlockAccess().getValueCommaKeyword_0()); }
		(
			{ before(grammarAccess.getKommaBlockAccess().getValueCommaKeyword_0()); }
			','
			{ after(grammarAccess.getKommaBlockAccess().getValueCommaKeyword_0()); }
		)
		{ after(grammarAccess.getKommaBlockAccess().getValueCommaKeyword_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ZuBlock__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getZuBlockAccess().getValueZuKeyword_0()); }
		(
			{ before(grammarAccess.getZuBlockAccess().getValueZuKeyword_0()); }
			'zu'
			{ after(grammarAccess.getZuBlockAccess().getValueZuKeyword_0()); }
		)
		{ after(grammarAccess.getZuBlockAccess().getValueZuKeyword_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MoechteBlock__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMoechteBlockAccess().getValueMöchteKeyword_0()); }
		(
			{ before(grammarAccess.getMoechteBlockAccess().getValueMöchteKeyword_0()); }
			'm\u00F6chte'
			{ after(grammarAccess.getMoechteBlockAccess().getValueMöchteKeyword_0()); }
		)
		{ after(grammarAccess.getMoechteBlockAccess().getValueMöchteKeyword_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__IchBlock__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getIchBlockAccess().getValueIchKeyword_0()); }
		(
			{ before(grammarAccess.getIchBlockAccess().getValueIchKeyword_0()); }
			'ich'
			{ after(grammarAccess.getIchBlockAccess().getValueIchKeyword_0()); }
		)
		{ after(grammarAccess.getIchBlockAccess().getValueIchKeyword_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AlsBlock__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAlsBlockAccess().getValueAlsKeyword_0()); }
		(
			{ before(grammarAccess.getAlsBlockAccess().getValueAlsKeyword_0()); }
			'als'
			{ after(grammarAccess.getAlsBlockAccess().getValueAlsKeyword_0()); }
		)
		{ after(grammarAccess.getAlsBlockAccess().getValueAlsKeyword_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__PunktBlock__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPunktBlockAccess().getValueFullStopKeyword_0()); }
		(
			{ before(grammarAccess.getPunktBlockAccess().getValueFullStopKeyword_0()); }
			'.'
			{ after(grammarAccess.getPunktBlockAccess().getValueFullStopKeyword_0()); }
		)
		{ after(grammarAccess.getPunktBlockAccess().getValueFullStopKeyword_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Substantiv__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getSubstantivAccess().getValueWORTTerminalRuleCall_0()); }
		RULE_WORT
		{ after(grammarAccess.getSubstantivAccess().getValueWORTTerminalRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Infinit__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInfinitAccess().getValueWORTTerminalRuleCall_0()); }
		RULE_WORT
		{ after(grammarAccess.getInfinitAccess().getValueWORTTerminalRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_WORT : ('a'..'z'|'A'..'Z'|'\u00C4'|'\u00D6'|'\u00DC'|'\u00E4'|'\u00F6'|'\u00FC'|'\u00DF')+;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
