/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BelegAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/htwdd/sf/beleg/s86320s86372/parser/antlr/internal/InternalBeleg.tokens");
	}
}
