/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractBelegValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage.eINSTANCE);
		return result;
	}
}
