/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.beleg;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegFactory
 * @model kind="package"
 * @generated
 */
public interface BelegPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "beleg";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.htwdd.de/sf/beleg/s86320/s86372/Beleg";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "beleg";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BelegPackage eINSTANCE = de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl.init();

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.ModelImpl
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Story</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STORY = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.StoryImpl <em>Story</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.StoryImpl
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getStory()
   * @generated
   */
  int STORY = 1;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__TITLE = 0;

  /**
   * The feature id for the '<em><b>Use</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__USE = 1;

  /**
   * The feature id for the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__ROLE = 2;

  /**
   * The feature id for the '<em><b>Goal</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__GOAL = 3;

  /**
   * The number of structural features of the '<em>Story</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.SImpl <em>S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.SImpl
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getS()
   * @generated
   */
  int S = 2;

  /**
   * The feature id for the '<em><b>Xe</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__XE = 0;

  /**
   * The feature id for the '<em><b>Ye</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__YE = 1;

  /**
   * The feature id for the '<em><b>Ze</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__ZE = 2;

  /**
   * The number of structural features of the '<em>S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.XPartImpl <em>XPart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.XPartImpl
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getXPart()
   * @generated
   */
  int XPART = 3;

  /**
   * The feature id for the '<em><b>Ti</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPART__TI = 0;

  /**
   * The number of structural features of the '<em>XPart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPART_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.TitleImpl <em>Title</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.TitleImpl
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getTitle()
   * @generated
   */
  int TITLE = 4;

  /**
   * The feature id for the '<em><b>Titel</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE__TITEL = 0;

  /**
   * The number of structural features of the '<em>Title</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.YPartImpl <em>YPart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.YPartImpl
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getYPart()
   * @generated
   */
  int YPART = 5;

  /**
   * The feature id for the '<em><b>Us</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YPART__US = 0;

  /**
   * The number of structural features of the '<em>YPart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YPART_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.UseImpl <em>Use</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.UseImpl
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getUse()
   * @generated
   */
  int USE = 6;

  /**
   * The feature id for the '<em><b>Nutzen</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE__NUTZEN = 0;

  /**
   * The number of structural features of the '<em>Use</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.ZPartImpl <em>ZPart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.ZPartImpl
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getZPart()
   * @generated
   */
  int ZPART = 7;

  /**
   * The feature id for the '<em><b>Rolle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZPART__ROLLE = 0;

  /**
   * The feature id for the '<em><b>Go</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZPART__GO = 1;

  /**
   * The number of structural features of the '<em>ZPart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZPART_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.GoalImpl <em>Goal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.GoalImpl
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getGoal()
   * @generated
   */
  int GOAL = 8;

  /**
   * The feature id for the '<em><b>Ziel</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL__ZIEL = 0;

  /**
   * The number of structural features of the '<em>Goal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOAL_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Model#getStory <em>Story</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Story</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Model#getStory()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Story();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Story <em>Story</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Story</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Story
   * @generated
   */
  EClass getStory();

  /**
   * Returns the meta object for the attribute list '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Title</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getTitle()
   * @see #getStory()
   * @generated
   */
  EAttribute getStory_Title();

  /**
   * Returns the meta object for the attribute list '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getUse <em>Use</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Use</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getUse()
   * @see #getStory()
   * @generated
   */
  EAttribute getStory_Use();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getRole()
   * @see #getStory()
   * @generated
   */
  EAttribute getStory_Role();

  /**
   * Returns the meta object for the attribute list '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getGoal <em>Goal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Goal</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getGoal()
   * @see #getStory()
   * @generated
   */
  EAttribute getStory_Goal();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.S <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>S</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.S
   * @generated
   */
  EClass getS();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.S#getXe <em>Xe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Xe</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.S#getXe()
   * @see #getS()
   * @generated
   */
  EReference getS_Xe();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.S#getYe <em>Ye</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ye</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.S#getYe()
   * @see #getS()
   * @generated
   */
  EReference getS_Ye();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.S#getZe <em>Ze</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ze</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.S#getZe()
   * @see #getS()
   * @generated
   */
  EReference getS_Ze();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.XPart <em>XPart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XPart</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.XPart
   * @generated
   */
  EClass getXPart();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.XPart#getTi <em>Ti</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ti</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.XPart#getTi()
   * @see #getXPart()
   * @generated
   */
  EReference getXPart_Ti();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Title <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Title</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Title
   * @generated
   */
  EClass getTitle();

  /**
   * Returns the meta object for the attribute list '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Title#getTitel <em>Titel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Titel</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Title#getTitel()
   * @see #getTitle()
   * @generated
   */
  EAttribute getTitle_Titel();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.YPart <em>YPart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>YPart</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.YPart
   * @generated
   */
  EClass getYPart();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.YPart#getUs <em>Us</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Us</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.YPart#getUs()
   * @see #getYPart()
   * @generated
   */
  EReference getYPart_Us();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Use <em>Use</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Use
   * @generated
   */
  EClass getUse();

  /**
   * Returns the meta object for the attribute list '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Use#getNutzen <em>Nutzen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Nutzen</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Use#getNutzen()
   * @see #getUse()
   * @generated
   */
  EAttribute getUse_Nutzen();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.ZPart <em>ZPart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ZPart</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.ZPart
   * @generated
   */
  EClass getZPart();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.ZPart#getRolle <em>Rolle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rolle</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.ZPart#getRolle()
   * @see #getZPart()
   * @generated
   */
  EAttribute getZPart_Rolle();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.ZPart#getGo <em>Go</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Go</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.ZPart#getGo()
   * @see #getZPart()
   * @generated
   */
  EReference getZPart_Go();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Goal <em>Goal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goal</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Goal
   * @generated
   */
  EClass getGoal();

  /**
   * Returns the meta object for the attribute list '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Goal#getZiel <em>Ziel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Ziel</em>'.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.Goal#getZiel()
   * @see #getGoal()
   * @generated
   */
  EAttribute getGoal_Ziel();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BelegFactory getBelegFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.ModelImpl
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Story</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STORY = eINSTANCE.getModel_Story();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.StoryImpl <em>Story</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.StoryImpl
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getStory()
     * @generated
     */
    EClass STORY = eINSTANCE.getStory();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORY__TITLE = eINSTANCE.getStory_Title();

    /**
     * The meta object literal for the '<em><b>Use</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORY__USE = eINSTANCE.getStory_Use();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORY__ROLE = eINSTANCE.getStory_Role();

    /**
     * The meta object literal for the '<em><b>Goal</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORY__GOAL = eINSTANCE.getStory_Goal();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.SImpl <em>S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.SImpl
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getS()
     * @generated
     */
    EClass S = eINSTANCE.getS();

    /**
     * The meta object literal for the '<em><b>Xe</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__XE = eINSTANCE.getS_Xe();

    /**
     * The meta object literal for the '<em><b>Ye</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__YE = eINSTANCE.getS_Ye();

    /**
     * The meta object literal for the '<em><b>Ze</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__ZE = eINSTANCE.getS_Ze();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.XPartImpl <em>XPart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.XPartImpl
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getXPart()
     * @generated
     */
    EClass XPART = eINSTANCE.getXPart();

    /**
     * The meta object literal for the '<em><b>Ti</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XPART__TI = eINSTANCE.getXPart_Ti();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.TitleImpl <em>Title</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.TitleImpl
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getTitle()
     * @generated
     */
    EClass TITLE = eINSTANCE.getTitle();

    /**
     * The meta object literal for the '<em><b>Titel</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITLE__TITEL = eINSTANCE.getTitle_Titel();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.YPartImpl <em>YPart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.YPartImpl
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getYPart()
     * @generated
     */
    EClass YPART = eINSTANCE.getYPart();

    /**
     * The meta object literal for the '<em><b>Us</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YPART__US = eINSTANCE.getYPart_Us();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.UseImpl <em>Use</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.UseImpl
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getUse()
     * @generated
     */
    EClass USE = eINSTANCE.getUse();

    /**
     * The meta object literal for the '<em><b>Nutzen</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE__NUTZEN = eINSTANCE.getUse_Nutzen();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.ZPartImpl <em>ZPart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.ZPartImpl
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getZPart()
     * @generated
     */
    EClass ZPART = eINSTANCE.getZPart();

    /**
     * The meta object literal for the '<em><b>Rolle</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZPART__ROLLE = eINSTANCE.getZPart_Rolle();

    /**
     * The meta object literal for the '<em><b>Go</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZPART__GO = eINSTANCE.getZPart_Go();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.GoalImpl <em>Goal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.GoalImpl
     * @see de.htwdd.sf.beleg.s86320.s86372.beleg.impl.BelegPackageImpl#getGoal()
     * @generated
     */
    EClass GOAL = eINSTANCE.getGoal();

    /**
     * The meta object literal for the '<em><b>Ziel</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOAL__ZIEL = eINSTANCE.getGoal_Ziel();

  }

} //BelegPackage
