/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.beleg;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Model#getStory <em>Story</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Story</b></em>' containment reference list.
   * The list contents are of type {@link de.htwdd.sf.beleg.s86320.s86372.beleg.S}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Story</em>' containment reference list.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getModel_Story()
   * @model containment="true"
   * @generated
   */
  EList<S> getStory();

} // Model
