/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.beleg;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nutzen</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Nutzen#getSubst <em>Subst</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Nutzen#getZuBlock <em>Zu Block</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Nutzen#getInfinit <em>Infinit</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getNutzen()
 * @model
 * @generated
 */
public interface Nutzen extends EObject
{
  /**
   * Returns the value of the '<em><b>Subst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subst</em>' containment reference.
   * @see #setSubst(Substantiv)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getNutzen_Subst()
   * @model containment="true"
   * @generated
   */
  Substantiv getSubst();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Nutzen#getSubst <em>Subst</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subst</em>' containment reference.
   * @see #getSubst()
   * @generated
   */
  void setSubst(Substantiv value);

  /**
   * Returns the value of the '<em><b>Zu Block</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zu Block</em>' attribute.
   * @see #setZuBlock(String)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getNutzen_ZuBlock()
   * @model
   * @generated
   */
  String getZuBlock();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Nutzen#getZuBlock <em>Zu Block</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zu Block</em>' attribute.
   * @see #getZuBlock()
   * @generated
   */
  void setZuBlock(String value);

  /**
   * Returns the value of the '<em><b>Infinit</b></em>' containment reference list.
   * The list contents are of type {@link de.htwdd.sf.beleg.s86320.s86372.beleg.Infinit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infinit</em>' containment reference list.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getNutzen_Infinit()
   * @model containment="true"
   * @generated
   */
  EList<Infinit> getInfinit();

} // Nutzen
