/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.beleg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>S</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.S#getXe <em>Xe</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.S#getYe <em>Ye</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.S#getZe <em>Ze</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getS()
 * @model
 * @generated
 */
public interface S extends EObject
{
  /**
   * Returns the value of the '<em><b>Xe</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xe</em>' containment reference.
   * @see #setXe(XPart)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getS_Xe()
   * @model containment="true"
   * @generated
   */
  XPart getXe();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.S#getXe <em>Xe</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xe</em>' containment reference.
   * @see #getXe()
   * @generated
   */
  void setXe(XPart value);

  /**
   * Returns the value of the '<em><b>Ye</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ye</em>' containment reference.
   * @see #setYe(YPart)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getS_Ye()
   * @model containment="true"
   * @generated
   */
  YPart getYe();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.S#getYe <em>Ye</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ye</em>' containment reference.
   * @see #getYe()
   * @generated
   */
  void setYe(YPart value);

  /**
   * Returns the value of the '<em><b>Ze</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ze</em>' containment reference.
   * @see #setZe(ZPart)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getS_Ze()
   * @model containment="true"
   * @generated
   */
  ZPart getZe();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.S#getZe <em>Ze</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ze</em>' containment reference.
   * @see #getZe()
   * @generated
   */
  void setZe(ZPart value);

} // S
