/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.beleg;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Story</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getTitle <em>Title</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getUse <em>Use</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getRole <em>Role</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getGoal <em>Goal</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getStory()
 * @model
 * @generated
 */
public interface Story extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute list.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getStory_Title()
   * @model unique="false"
   * @generated
   */
  EList<String> getTitle();

  /**
   * Returns the value of the '<em><b>Use</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use</em>' attribute list.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getStory_Use()
   * @model unique="false"
   * @generated
   */
  EList<String> getUse();

  /**
   * Returns the value of the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' attribute.
   * @see #setRole(String)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getStory_Role()
   * @model
   * @generated
   */
  String getRole();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.Story#getRole <em>Role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' attribute.
   * @see #getRole()
   * @generated
   */
  void setRole(String value);

  /**
   * Returns the value of the '<em><b>Goal</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goal</em>' attribute list.
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getStory_Goal()
   * @model unique="false"
   * @generated
   */
  EList<String> getGoal();

} // Story
