/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.beleg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User Story Um</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.User_Story_Um#getTitle <em>Title</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.User_Story_Um#getUse <em>Use</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.User_Story_Um#getRole <em>Role</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.User_Story_Um#getGoal <em>Goal</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getUser_Story_Um()
 * @model
 * @generated
 */
public interface User_Story_Um extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' containment reference.
   * @see #setTitle(Titel)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getUser_Story_Um_Title()
   * @model containment="true"
   * @generated
   */
  Titel getTitle();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.User_Story_Um#getTitle <em>Title</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' containment reference.
   * @see #getTitle()
   * @generated
   */
  void setTitle(Titel value);

  /**
   * Returns the value of the '<em><b>Use</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use</em>' containment reference.
   * @see #setUse(Nutzen)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getUser_Story_Um_Use()
   * @model containment="true"
   * @generated
   */
  Nutzen getUse();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.User_Story_Um#getUse <em>Use</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Use</em>' containment reference.
   * @see #getUse()
   * @generated
   */
  void setUse(Nutzen value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' containment reference.
   * @see #setRole(Rolle)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getUser_Story_Um_Role()
   * @model containment="true"
   * @generated
   */
  Rolle getRole();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.User_Story_Um#getRole <em>Role</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' containment reference.
   * @see #getRole()
   * @generated
   */
  void setRole(Rolle value);

  /**
   * Returns the value of the '<em><b>Goal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goal</em>' containment reference.
   * @see #setGoal(Ziel)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getUser_Story_Um_Goal()
   * @model containment="true"
   * @generated
   */
  Ziel getGoal();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.User_Story_Um#getGoal <em>Goal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Goal</em>' containment reference.
   * @see #getGoal()
   * @generated
   */
  void setGoal(Ziel value);

} // User_Story_Um
