/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.beleg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>YPart</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.YPart#getUs <em>Us</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getYPart()
 * @model
 * @generated
 */
public interface YPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Us</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Us</em>' containment reference.
   * @see #setUs(Use)
   * @see de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage#getYPart_Us()
   * @model containment="true"
   * @generated
   */
  Use getUs();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320.s86372.beleg.YPart#getUs <em>Us</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Us</em>' containment reference.
   * @see #getUs()
   * @generated
   */
  void setUs(Use value);

} // YPart
