/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.beleg.util;

import de.htwdd.sf.beleg.s86320s86372.beleg.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage
 * @generated
 */
public class BelegAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static BelegPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BelegAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = BelegPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BelegSwitch<Adapter> modelSwitch =
    new BelegSwitch<Adapter>()
    {
      @Override
      public Adapter caseModel(Model object)
      {
        return createModelAdapter();
      }
      @Override
      public Adapter caseUser_Story_Um(User_Story_Um object)
      {
        return createUser_Story_UmAdapter();
      }
      @Override
      public Adapter caseTitel(Titel object)
      {
        return createTitelAdapter();
      }
      @Override
      public Adapter caseText(Text object)
      {
        return createTextAdapter();
      }
      @Override
      public Adapter caseNutzen(Nutzen object)
      {
        return createNutzenAdapter();
      }
      @Override
      public Adapter caseRolle(Rolle object)
      {
        return createRolleAdapter();
      }
      @Override
      public Adapter caseZiel(Ziel object)
      {
        return createZielAdapter();
      }
      @Override
      public Adapter caseDoppelPunktBlock(DoppelPunktBlock object)
      {
        return createDoppelPunktBlockAdapter();
      }
      @Override
      public Adapter caseUmBlock(UmBlock object)
      {
        return createUmBlockAdapter();
      }
      @Override
      public Adapter caseKommaBlock(KommaBlock object)
      {
        return createKommaBlockAdapter();
      }
      @Override
      public Adapter caseZuBlock(ZuBlock object)
      {
        return createZuBlockAdapter();
      }
      @Override
      public Adapter caseMoechteBlock(MoechteBlock object)
      {
        return createMoechteBlockAdapter();
      }
      @Override
      public Adapter caseIchBlock(IchBlock object)
      {
        return createIchBlockAdapter();
      }
      @Override
      public Adapter caseAlsBlock(AlsBlock object)
      {
        return createAlsBlockAdapter();
      }
      @Override
      public Adapter casePunktBlock(PunktBlock object)
      {
        return createPunktBlockAdapter();
      }
      @Override
      public Adapter caseSubstantiv(Substantiv object)
      {
        return createSubstantivAdapter();
      }
      @Override
      public Adapter caseInfinit(Infinit object)
      {
        return createInfinitAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Model
   * @generated
   */
  public Adapter createModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um <em>User Story Um</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um
   * @generated
   */
  public Adapter createUser_Story_UmAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Titel <em>Titel</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Titel
   * @generated
   */
  public Adapter createTitelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Text
   * @generated
   */
  public Adapter createTextAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen <em>Nutzen</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen
   * @generated
   */
  public Adapter createNutzenAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Rolle <em>Rolle</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Rolle
   * @generated
   */
  public Adapter createRolleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Ziel <em>Ziel</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Ziel
   * @generated
   */
  public Adapter createZielAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.DoppelPunktBlock <em>Doppel Punkt Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.DoppelPunktBlock
   * @generated
   */
  public Adapter createDoppelPunktBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.UmBlock <em>Um Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.UmBlock
   * @generated
   */
  public Adapter createUmBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.KommaBlock <em>Komma Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.KommaBlock
   * @generated
   */
  public Adapter createKommaBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.ZuBlock <em>Zu Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.ZuBlock
   * @generated
   */
  public Adapter createZuBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.MoechteBlock <em>Moechte Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.MoechteBlock
   * @generated
   */
  public Adapter createMoechteBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.IchBlock <em>Ich Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.IchBlock
   * @generated
   */
  public Adapter createIchBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.AlsBlock <em>Als Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.AlsBlock
   * @generated
   */
  public Adapter createAlsBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.PunktBlock <em>Punkt Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.PunktBlock
   * @generated
   */
  public Adapter createPunktBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Substantiv <em>Substantiv</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Substantiv
   * @generated
   */
  public Adapter createSubstantivAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Infinit <em>Infinit</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Infinit
   * @generated
   */
  public Adapter createInfinitAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //BelegAdapterFactory
