/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.ui;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s86320s86372.ui.internal.S86320s86372Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BelegExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(S86320s86372Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		S86320s86372Activator activator = S86320s86372Activator.getInstance();
		return activator != null ? activator.getInjector(S86320s86372Activator.DE_HTWDD_SF_BELEG_S86320S86372_BELEG) : null;
	}

}
