/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BelegGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.Model");
		private final Assignment cStoryAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStoryUser_Story_UmParserRuleCall_0 = (RuleCall)cStoryAssignment.eContents().get(0);
		
		//Model:
		//    story+=User_Story_Um+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//story+=User_Story_Um+
		public Assignment getStoryAssignment() { return cStoryAssignment; }
		
		//User_Story_Um
		public RuleCall getStoryUser_Story_UmParserRuleCall_0() { return cStoryUser_Story_UmParserRuleCall_0; }
	}
	public class User_Story_UmElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.User_Story_Um");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTitleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTitleTitelParserRuleCall_0_0 = (RuleCall)cTitleAssignment_0.eContents().get(0);
		private final Assignment cDoppelpunktAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDoppelpunktDoppelPunktBlockParserRuleCall_1_0 = (RuleCall)cDoppelpunktAssignment_1.eContents().get(0);
		private final Assignment cUmAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cUmUmBlockParserRuleCall_2_0 = (RuleCall)cUmAssignment_2.eContents().get(0);
		private final Assignment cUseAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUseNutzenParserRuleCall_3_0 = (RuleCall)cUseAssignment_3.eContents().get(0);
		private final Assignment cKommaAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cKommaKommaBlockParserRuleCall_4_0 = (RuleCall)cKommaAssignment_4.eContents().get(0);
		private final Assignment cMoechteAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMoechteMoechteBlockParserRuleCall_5_0 = (RuleCall)cMoechteAssignment_5.eContents().get(0);
		private final Assignment cIchAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cIchIchBlockParserRuleCall_6_0 = (RuleCall)cIchAssignment_6.eContents().get(0);
		private final Assignment cAlsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAlsAlsBlockParserRuleCall_7_0 = (RuleCall)cAlsAssignment_7.eContents().get(0);
		private final Assignment cRoleAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cRoleRolleParserRuleCall_8_0 = (RuleCall)cRoleAssignment_8.eContents().get(0);
		private final Assignment cGoalAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cGoalZielParserRuleCall_9_0 = (RuleCall)cGoalAssignment_9.eContents().get(0);
		private final Assignment cPunktAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cPunktPunktBlockParserRuleCall_10_0 = (RuleCall)cPunktAssignment_10.eContents().get(0);
		
		////Null testen:
		////Als Bearbeiter möchte ich Anträge einsehen, um Projekte zu bezuschussen.
		////
		////Eins testen:
		////Als Bearbeiter möchte ich Pdf exportieren, um Dokumente zuückzusenden.
		////
		////Zwei testen:
		////Als Bearbeiter möchte ich Dokumente kommentieren, um Anmerkungen hinzuzufügen.
		////
		////Drei testen:
		////Als Bediener möchte ich Roboter steuern, um Kabel zurechtzuzupfen.
		////
		////Vier testen:
		////Um Projekte zu bezuschussen, möchte ich als Bearbeiter Anträge einsehen.
		////
		////Fünf testen:
		////Um Dokumente zurückzusenden, möchte ich als Bearbeiter Dateien exportieren.
		////
		////Sechs testen:
		////Um Anmerkungen hinzuzufügen, möchte ich als Bearbeiter Dokumente kommentieren.
		////
		////Sieben testen:
		////Um Kabel zurechtzuzupfen, möchte ich als Bediener Roboter steuern.
		//// <Titel>: Um <Nutzen>, möchte ich als <Rolle> <Ziel/Wunsch>.
		//User_Story_Um:
		//    title = Titel
		//    doppelpunkt = DoppelPunktBlock
		//    um = UmBlock
		//    use = Nutzen
		//    komma = KommaBlock
		//    moechte = MoechteBlock
		//    ich = IchBlock
		//    als = AlsBlock
		//    role = Rolle
		//    goal = Ziel
		//    punkt = PunktBlock
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//title = Titel
		//doppelpunkt = DoppelPunktBlock
		//um = UmBlock
		//use = Nutzen
		//komma = KommaBlock
		//moechte = MoechteBlock
		//ich = IchBlock
		//als = AlsBlock
		//role = Rolle
		//goal = Ziel
		//punkt = PunktBlock
		public Group getGroup() { return cGroup; }
		
		//title = Titel
		public Assignment getTitleAssignment_0() { return cTitleAssignment_0; }
		
		//Titel
		public RuleCall getTitleTitelParserRuleCall_0_0() { return cTitleTitelParserRuleCall_0_0; }
		
		//doppelpunkt = DoppelPunktBlock
		public Assignment getDoppelpunktAssignment_1() { return cDoppelpunktAssignment_1; }
		
		//DoppelPunktBlock
		public RuleCall getDoppelpunktDoppelPunktBlockParserRuleCall_1_0() { return cDoppelpunktDoppelPunktBlockParserRuleCall_1_0; }
		
		//um = UmBlock
		public Assignment getUmAssignment_2() { return cUmAssignment_2; }
		
		//UmBlock
		public RuleCall getUmUmBlockParserRuleCall_2_0() { return cUmUmBlockParserRuleCall_2_0; }
		
		//use = Nutzen
		public Assignment getUseAssignment_3() { return cUseAssignment_3; }
		
		//Nutzen
		public RuleCall getUseNutzenParserRuleCall_3_0() { return cUseNutzenParserRuleCall_3_0; }
		
		//komma = KommaBlock
		public Assignment getKommaAssignment_4() { return cKommaAssignment_4; }
		
		//KommaBlock
		public RuleCall getKommaKommaBlockParserRuleCall_4_0() { return cKommaKommaBlockParserRuleCall_4_0; }
		
		//moechte = MoechteBlock
		public Assignment getMoechteAssignment_5() { return cMoechteAssignment_5; }
		
		//MoechteBlock
		public RuleCall getMoechteMoechteBlockParserRuleCall_5_0() { return cMoechteMoechteBlockParserRuleCall_5_0; }
		
		//ich = IchBlock
		public Assignment getIchAssignment_6() { return cIchAssignment_6; }
		
		//IchBlock
		public RuleCall getIchIchBlockParserRuleCall_6_0() { return cIchIchBlockParserRuleCall_6_0; }
		
		//als = AlsBlock
		public Assignment getAlsAssignment_7() { return cAlsAssignment_7; }
		
		//AlsBlock
		public RuleCall getAlsAlsBlockParserRuleCall_7_0() { return cAlsAlsBlockParserRuleCall_7_0; }
		
		//role = Rolle
		public Assignment getRoleAssignment_8() { return cRoleAssignment_8; }
		
		//Rolle
		public RuleCall getRoleRolleParserRuleCall_8_0() { return cRoleRolleParserRuleCall_8_0; }
		
		//goal = Ziel
		public Assignment getGoalAssignment_9() { return cGoalAssignment_9; }
		
		//Ziel
		public RuleCall getGoalZielParserRuleCall_9_0() { return cGoalZielParserRuleCall_9_0; }
		
		//punkt = PunktBlock
		public Assignment getPunktAssignment_10() { return cPunktAssignment_10; }
		
		//PunktBlock
		public RuleCall getPunktPunktBlockParserRuleCall_10_0() { return cPunktPunktBlockParserRuleCall_10_0; }
	}
	public class TitelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.Titel");
		private final Assignment cTextpartAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTextpartTextParserRuleCall_0 = (RuleCall)cTextpartAssignment.eContents().get(0);
		
		//Titel:
		//    textpart += Text+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//textpart += Text+
		public Assignment getTextpartAssignment() { return cTextpartAssignment; }
		
		//Text
		public RuleCall getTextpartTextParserRuleCall_0() { return cTextpartTextParserRuleCall_0; }
	}
	public class TextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.Text");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueWORTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Text:
		//    value = WORT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value = WORT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//WORT
		public RuleCall getValueWORTTerminalRuleCall_0() { return cValueWORTTerminalRuleCall_0; }
	}
	public class NutzenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.Nutzen");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubstAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubstSubstantivParserRuleCall_0_0 = (RuleCall)cSubstAssignment_0.eContents().get(0);
		private final Assignment cZuAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cZuZuBlockParserRuleCall_1_0 = (RuleCall)cZuAssignment_1.eContents().get(0);
		private final Assignment cInfinitAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInfinitInfinitParserRuleCall_2_0 = (RuleCall)cInfinitAssignment_2.eContents().get(0);
		
		//Nutzen:
		//    subst = Substantiv
		//    zu = ZuBlock?
		//    infinit += Infinit+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//subst = Substantiv
		//zu = ZuBlock?
		//infinit += Infinit+
		public Group getGroup() { return cGroup; }
		
		//subst = Substantiv
		public Assignment getSubstAssignment_0() { return cSubstAssignment_0; }
		
		//Substantiv
		public RuleCall getSubstSubstantivParserRuleCall_0_0() { return cSubstSubstantivParserRuleCall_0_0; }
		
		//zu = ZuBlock?
		public Assignment getZuAssignment_1() { return cZuAssignment_1; }
		
		//ZuBlock
		public RuleCall getZuZuBlockParserRuleCall_1_0() { return cZuZuBlockParserRuleCall_1_0; }
		
		//infinit += Infinit+
		public Assignment getInfinitAssignment_2() { return cInfinitAssignment_2; }
		
		//Infinit
		public RuleCall getInfinitInfinitParserRuleCall_2_0() { return cInfinitInfinitParserRuleCall_2_0; }
	}
	public class RolleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.Rolle");
		private final Assignment cSubstAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cSubstSubstantivParserRuleCall_0 = (RuleCall)cSubstAssignment.eContents().get(0);
		
		//Rolle:
		//    subst = Substantiv
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//subst = Substantiv
		public Assignment getSubstAssignment() { return cSubstAssignment; }
		
		//Substantiv
		public RuleCall getSubstSubstantivParserRuleCall_0() { return cSubstSubstantivParserRuleCall_0; }
	}
	public class ZielElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.Ziel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubstAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubstSubstantivParserRuleCall_0_0 = (RuleCall)cSubstAssignment_0.eContents().get(0);
		private final Assignment cInfinitAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInfinitInfinitParserRuleCall_1_0 = (RuleCall)cInfinitAssignment_1.eContents().get(0);
		
		//Ziel:
		//    subst = Substantiv
		//    infinit += Infinit+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//subst = Substantiv
		//infinit += Infinit+
		public Group getGroup() { return cGroup; }
		
		//subst = Substantiv
		public Assignment getSubstAssignment_0() { return cSubstAssignment_0; }
		
		//Substantiv
		public RuleCall getSubstSubstantivParserRuleCall_0_0() { return cSubstSubstantivParserRuleCall_0_0; }
		
		//infinit += Infinit+
		public Assignment getInfinitAssignment_1() { return cInfinitAssignment_1; }
		
		//Infinit
		public RuleCall getInfinitInfinitParserRuleCall_1_0() { return cInfinitInfinitParserRuleCall_1_0; }
	}
	public class DoppelPunktBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.DoppelPunktBlock");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueColonKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//DoppelPunktBlock:
		//    value = ':'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value = ':'
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//':'
		public Keyword getValueColonKeyword_0() { return cValueColonKeyword_0; }
	}
	public class UmBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.UmBlock");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueUmKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//UmBlock:
		//    value = 'Um'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value = 'Um'
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//'Um'
		public Keyword getValueUmKeyword_0() { return cValueUmKeyword_0; }
	}
	public class KommaBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.KommaBlock");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueCommaKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//KommaBlock:
		//    value = ','
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value = ','
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//','
		public Keyword getValueCommaKeyword_0() { return cValueCommaKeyword_0; }
	}
	public class ZuBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.ZuBlock");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueZuKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//ZuBlock:
		//    value ='zu'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value ='zu'
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//'zu'
		public Keyword getValueZuKeyword_0() { return cValueZuKeyword_0; }
	}
	public class MoechteBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.MoechteBlock");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueMöchteKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//MoechteBlock:
		//    value ='möchte'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value ='möchte'
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//'möchte'
		public Keyword getValueMöchteKeyword_0() { return cValueMöchteKeyword_0; }
	}
	public class IchBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.IchBlock");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueIchKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//IchBlock:
		//    value ='ich'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value ='ich'
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//'ich'
		public Keyword getValueIchKeyword_0() { return cValueIchKeyword_0; }
	}
	public class AlsBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.AlsBlock");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueAlsKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//AlsBlock:
		//    value ='als'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value ='als'
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//'als'
		public Keyword getValueAlsKeyword_0() { return cValueAlsKeyword_0; }
	}
	public class PunktBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.PunktBlock");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueFullStopKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//PunktBlock:
		//    value ='.'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value ='.'
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//'.'
		public Keyword getValueFullStopKeyword_0() { return cValueFullStopKeyword_0; }
	}
	public class SubstantivElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.Substantiv");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueWORTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Substantiv:
		//    value = WORT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value = WORT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//WORT
		public RuleCall getValueWORTTerminalRuleCall_0() { return cValueWORTTerminalRuleCall_0; }
	}
	public class InfinitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.Infinit");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueWORTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Infinit:
		//    value = WORT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value = WORT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//WORT
		public RuleCall getValueWORTTerminalRuleCall_0() { return cValueWORTTerminalRuleCall_0; }
	}
	
	
	private final ModelElements pModel;
	private final User_Story_UmElements pUser_Story_Um;
	private final TitelElements pTitel;
	private final TextElements pText;
	private final NutzenElements pNutzen;
	private final RolleElements pRolle;
	private final ZielElements pZiel;
	private final DoppelPunktBlockElements pDoppelPunktBlock;
	private final UmBlockElements pUmBlock;
	private final KommaBlockElements pKommaBlock;
	private final ZuBlockElements pZuBlock;
	private final MoechteBlockElements pMoechteBlock;
	private final IchBlockElements pIchBlock;
	private final AlsBlockElements pAlsBlock;
	private final PunktBlockElements pPunktBlock;
	private final SubstantivElements pSubstantiv;
	private final InfinitElements pInfinit;
	private final TerminalRule tWORT;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BelegGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pUser_Story_Um = new User_Story_UmElements();
		this.pTitel = new TitelElements();
		this.pText = new TextElements();
		this.pNutzen = new NutzenElements();
		this.pRolle = new RolleElements();
		this.pZiel = new ZielElements();
		this.pDoppelPunktBlock = new DoppelPunktBlockElements();
		this.pUmBlock = new UmBlockElements();
		this.pKommaBlock = new KommaBlockElements();
		this.pZuBlock = new ZuBlockElements();
		this.pMoechteBlock = new MoechteBlockElements();
		this.pIchBlock = new IchBlockElements();
		this.pAlsBlock = new AlsBlockElements();
		this.pPunktBlock = new PunktBlockElements();
		this.pSubstantiv = new SubstantivElements();
		this.pInfinit = new InfinitElements();
		this.tWORT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320s86372.Beleg.WORT");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.htwdd.sf.beleg.s86320s86372.Beleg".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    story+=User_Story_Um+
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	////Null testen:
	////Als Bearbeiter möchte ich Anträge einsehen, um Projekte zu bezuschussen.
	////
	////Eins testen:
	////Als Bearbeiter möchte ich Pdf exportieren, um Dokumente zuückzusenden.
	////
	////Zwei testen:
	////Als Bearbeiter möchte ich Dokumente kommentieren, um Anmerkungen hinzuzufügen.
	////
	////Drei testen:
	////Als Bediener möchte ich Roboter steuern, um Kabel zurechtzuzupfen.
	////
	////Vier testen:
	////Um Projekte zu bezuschussen, möchte ich als Bearbeiter Anträge einsehen.
	////
	////Fünf testen:
	////Um Dokumente zurückzusenden, möchte ich als Bearbeiter Dateien exportieren.
	////
	////Sechs testen:
	////Um Anmerkungen hinzuzufügen, möchte ich als Bearbeiter Dokumente kommentieren.
	////
	////Sieben testen:
	////Um Kabel zurechtzuzupfen, möchte ich als Bediener Roboter steuern.
	//// <Titel>: Um <Nutzen>, möchte ich als <Rolle> <Ziel/Wunsch>.
	//User_Story_Um:
	//    title = Titel
	//    doppelpunkt = DoppelPunktBlock
	//    um = UmBlock
	//    use = Nutzen
	//    komma = KommaBlock
	//    moechte = MoechteBlock
	//    ich = IchBlock
	//    als = AlsBlock
	//    role = Rolle
	//    goal = Ziel
	//    punkt = PunktBlock
	//;
	public User_Story_UmElements getUser_Story_UmAccess() {
		return pUser_Story_Um;
	}
	
	public ParserRule getUser_Story_UmRule() {
		return getUser_Story_UmAccess().getRule();
	}
	
	//Titel:
	//    textpart += Text+
	//;
	public TitelElements getTitelAccess() {
		return pTitel;
	}
	
	public ParserRule getTitelRule() {
		return getTitelAccess().getRule();
	}
	
	//Text:
	//    value = WORT
	//;
	public TextElements getTextAccess() {
		return pText;
	}
	
	public ParserRule getTextRule() {
		return getTextAccess().getRule();
	}
	
	//Nutzen:
	//    subst = Substantiv
	//    zu = ZuBlock?
	//    infinit += Infinit+
	//;
	public NutzenElements getNutzenAccess() {
		return pNutzen;
	}
	
	public ParserRule getNutzenRule() {
		return getNutzenAccess().getRule();
	}
	
	//Rolle:
	//    subst = Substantiv
	//;
	public RolleElements getRolleAccess() {
		return pRolle;
	}
	
	public ParserRule getRolleRule() {
		return getRolleAccess().getRule();
	}
	
	//Ziel:
	//    subst = Substantiv
	//    infinit += Infinit+
	//;
	public ZielElements getZielAccess() {
		return pZiel;
	}
	
	public ParserRule getZielRule() {
		return getZielAccess().getRule();
	}
	
	//DoppelPunktBlock:
	//    value = ':'
	//;
	public DoppelPunktBlockElements getDoppelPunktBlockAccess() {
		return pDoppelPunktBlock;
	}
	
	public ParserRule getDoppelPunktBlockRule() {
		return getDoppelPunktBlockAccess().getRule();
	}
	
	//UmBlock:
	//    value = 'Um'
	//;
	public UmBlockElements getUmBlockAccess() {
		return pUmBlock;
	}
	
	public ParserRule getUmBlockRule() {
		return getUmBlockAccess().getRule();
	}
	
	//KommaBlock:
	//    value = ','
	//;
	public KommaBlockElements getKommaBlockAccess() {
		return pKommaBlock;
	}
	
	public ParserRule getKommaBlockRule() {
		return getKommaBlockAccess().getRule();
	}
	
	//ZuBlock:
	//    value ='zu'
	//;
	public ZuBlockElements getZuBlockAccess() {
		return pZuBlock;
	}
	
	public ParserRule getZuBlockRule() {
		return getZuBlockAccess().getRule();
	}
	
	//MoechteBlock:
	//    value ='möchte'
	//;
	public MoechteBlockElements getMoechteBlockAccess() {
		return pMoechteBlock;
	}
	
	public ParserRule getMoechteBlockRule() {
		return getMoechteBlockAccess().getRule();
	}
	
	//IchBlock:
	//    value ='ich'
	//;
	public IchBlockElements getIchBlockAccess() {
		return pIchBlock;
	}
	
	public ParserRule getIchBlockRule() {
		return getIchBlockAccess().getRule();
	}
	
	//AlsBlock:
	//    value ='als'
	//;
	public AlsBlockElements getAlsBlockAccess() {
		return pAlsBlock;
	}
	
	public ParserRule getAlsBlockRule() {
		return getAlsBlockAccess().getRule();
	}
	
	//PunktBlock:
	//    value ='.'
	//;
	public PunktBlockElements getPunktBlockAccess() {
		return pPunktBlock;
	}
	
	public ParserRule getPunktBlockRule() {
		return getPunktBlockAccess().getRule();
	}
	
	//Substantiv:
	//    value = WORT
	//;
	public SubstantivElements getSubstantivAccess() {
		return pSubstantiv;
	}
	
	public ParserRule getSubstantivRule() {
		return getSubstantivAccess().getRule();
	}
	
	//Infinit:
	//    value = WORT
	//;
	public InfinitElements getInfinitAccess() {
		return pInfinit;
	}
	
	public ParserRule getInfinitRule() {
		return getInfinitAccess().getRule();
	}
	
	//terminal WORT:
	//     ('a'..'z' | 'A'..'Z' | 'Ä' | 'Ö' | 'Ü' | 'ä' | 'ö' | 'ü' | 'ß')+
	//;
	public TerminalRule getWORTRule() {
		return tWORT;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
