/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BelegGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Model");
		private final Assignment cStoryAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStoryUser_Story_UmParserRuleCall_0 = (RuleCall)cStoryAssignment.eContents().get(0);
		
		//Model:
		//    story+=User_Story_Um*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//story+=User_Story_Um*
		public Assignment getStoryAssignment() { return cStoryAssignment; }
		
		//User_Story_Um
		public RuleCall getStoryUser_Story_UmParserRuleCall_0() { return cStoryUser_Story_UmParserRuleCall_0; }
	}
	public class User_Story_UmElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.User_Story_Um");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTitleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTitleTitelParserRuleCall_0_0 = (RuleCall)cTitleAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cUmKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUseAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUseNutzenParserRuleCall_3_0 = (RuleCall)cUseAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cMöchteKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cIchKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cAlsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cRoleAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cRoleRolleParserRuleCall_8_0 = (RuleCall)cRoleAssignment_8.eContents().get(0);
		private final Assignment cGoalAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cGoalZielParserRuleCall_9_0 = (RuleCall)cGoalAssignment_9.eContents().get(0);
		private final Keyword cFullStopKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		////Null testen:
		////Als Bearbeiter möchte ich Anträge einsehen, um Projekte zu bezuschussen.
		////
		////Eins testen:
		////Als Bearbeiter möchte ich Pdf exportieren, um Dokumente zuückzusenden.
		////
		////Zwei testen:
		////Als Bearbeiter möchte ich Dokumente kommentieren, um Anmerkungen hinzuzufügen.
		////
		////Drei testen:
		////Als Bediener möchte ich Roboter steuern, um Kabel zurechtzuzupfen.
		////
		////Vier testen:
		////Um Projekte zu bezuschussen, möchte ich als Bearbeiter Anträge einsehen.
		////
		////Fünf testen:
		////Um Dokumente zurückzusenden, möchte ich als Bearbeiter Dateien exportieren.
		////
		////Sechs testen:
		////Um Anmerkungen hinzuzufügen, möchte ich als Bearbeiter Dokumente kommentieren.
		////
		////Sieben testen:
		////Um Kabel zurechtzuzupfen, möchte ich als Bediener Roboter steuern.
		//// <Titel>: Um <Nutzen>, möchte ich als <Rolle> <Ziel/Wunsch>.
		//User_Story_Um:
		//    title=Titel ':'
		//    'Um' use=Nutzen ','
		//    'möchte' 'ich' 'als'
		//    role=Rolle
		//    goal=Ziel
		//    '.'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//title=Titel ':'
		//'Um' use=Nutzen ','
		//'möchte' 'ich' 'als'
		//role=Rolle
		//goal=Ziel
		//'.'
		public Group getGroup() { return cGroup; }
		
		//title=Titel
		public Assignment getTitleAssignment_0() { return cTitleAssignment_0; }
		
		//Titel
		public RuleCall getTitleTitelParserRuleCall_0_0() { return cTitleTitelParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//'Um'
		public Keyword getUmKeyword_2() { return cUmKeyword_2; }
		
		//use=Nutzen
		public Assignment getUseAssignment_3() { return cUseAssignment_3; }
		
		//Nutzen
		public RuleCall getUseNutzenParserRuleCall_3_0() { return cUseNutzenParserRuleCall_3_0; }
		
		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//'möchte'
		public Keyword getMöchteKeyword_5() { return cMöchteKeyword_5; }
		
		//'ich'
		public Keyword getIchKeyword_6() { return cIchKeyword_6; }
		
		//'als'
		public Keyword getAlsKeyword_7() { return cAlsKeyword_7; }
		
		//role=Rolle
		public Assignment getRoleAssignment_8() { return cRoleAssignment_8; }
		
		//Rolle
		public RuleCall getRoleRolleParserRuleCall_8_0() { return cRoleRolleParserRuleCall_8_0; }
		
		//goal=Ziel
		public Assignment getGoalAssignment_9() { return cGoalAssignment_9; }
		
		//Ziel
		public RuleCall getGoalZielParserRuleCall_9_0() { return cGoalZielParserRuleCall_9_0; }
		
		//'.'
		public Keyword getFullStopKeyword_10() { return cFullStopKeyword_10; }
	}
	public class TitelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Titel");
		private final Assignment cTextpartAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTextpartTextParserRuleCall_0 = (RuleCall)cTextpartAssignment.eContents().get(0);
		
		//Titel:
		//    textpart += Text+
		////    subst=Substantiv
		////    infinit += Infinit+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//textpart += Text+
		public Assignment getTextpartAssignment() { return cTextpartAssignment; }
		
		//Text
		public RuleCall getTextpartTextParserRuleCall_0() { return cTextpartTextParserRuleCall_0; }
	}
	public class TextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Text");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueWORTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Text:
		//    value = WORT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value = WORT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//WORT
		public RuleCall getValueWORTTerminalRuleCall_0() { return cValueWORTTerminalRuleCall_0; }
	}
	public class NutzenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Nutzen");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubstAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubstSubstantivParserRuleCall_0_0 = (RuleCall)cSubstAssignment_0.eContents().get(0);
		private final Assignment cZuBlockAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cZuBlockZuBlockParserRuleCall_1_0 = (RuleCall)cZuBlockAssignment_1.eContents().get(0);
		private final Assignment cInfinitAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInfinitInfinitParserRuleCall_2_0 = (RuleCall)cInfinitAssignment_2.eContents().get(0);
		
		//Nutzen:
		//    subst = Substantiv
		//    zuBlock=ZuBlock?
		//    infinit += Infinit+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//subst = Substantiv
		//zuBlock=ZuBlock?
		//infinit += Infinit+
		public Group getGroup() { return cGroup; }
		
		//subst = Substantiv
		public Assignment getSubstAssignment_0() { return cSubstAssignment_0; }
		
		//Substantiv
		public RuleCall getSubstSubstantivParserRuleCall_0_0() { return cSubstSubstantivParserRuleCall_0_0; }
		
		//zuBlock=ZuBlock?
		public Assignment getZuBlockAssignment_1() { return cZuBlockAssignment_1; }
		
		//ZuBlock
		public RuleCall getZuBlockZuBlockParserRuleCall_1_0() { return cZuBlockZuBlockParserRuleCall_1_0; }
		
		//infinit += Infinit+
		public Assignment getInfinitAssignment_2() { return cInfinitAssignment_2; }
		
		//Infinit
		public RuleCall getInfinitInfinitParserRuleCall_2_0() { return cInfinitInfinitParserRuleCall_2_0; }
	}
	public class ZuBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.ZuBlock");
		private final Keyword cZuKeyword = (Keyword)rule.eContents().get(1);
		
		//ZuBlock:
		//    'zu'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'zu'
		public Keyword getZuKeyword() { return cZuKeyword; }
	}
	public class RolleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Rolle");
		private final Assignment cSubstAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cSubstSubstantivParserRuleCall_0 = (RuleCall)cSubstAssignment.eContents().get(0);
		
		//Rolle:
		//    subst = Substantiv
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//subst = Substantiv
		public Assignment getSubstAssignment() { return cSubstAssignment; }
		
		//Substantiv
		public RuleCall getSubstSubstantivParserRuleCall_0() { return cSubstSubstantivParserRuleCall_0; }
	}
	public class ZielElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Ziel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubstAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubstSubstantivParserRuleCall_0_0 = (RuleCall)cSubstAssignment_0.eContents().get(0);
		private final Assignment cInfinitAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInfinitInfinitParserRuleCall_1_0 = (RuleCall)cInfinitAssignment_1.eContents().get(0);
		
		//Ziel:
		//    subst = Substantiv
		//    infinit += Infinit+
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//subst = Substantiv
		//infinit += Infinit+
		public Group getGroup() { return cGroup; }
		
		//subst = Substantiv
		public Assignment getSubstAssignment_0() { return cSubstAssignment_0; }
		
		//Substantiv
		public RuleCall getSubstSubstantivParserRuleCall_0_0() { return cSubstSubstantivParserRuleCall_0_0; }
		
		//infinit += Infinit+
		public Assignment getInfinitAssignment_1() { return cInfinitAssignment_1; }
		
		//Infinit
		public RuleCall getInfinitInfinitParserRuleCall_1_0() { return cInfinitInfinitParserRuleCall_1_0; }
	}
	public class SubstantivElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Substantiv");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueWORTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Substantiv:
		//    value = WORT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value = WORT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//WORT
		public RuleCall getValueWORTTerminalRuleCall_0() { return cValueWORTTerminalRuleCall_0; }
	}
	public class InfinitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Infinit");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueWORTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Infinit:
		//    value = WORT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value = WORT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//WORT
		public RuleCall getValueWORTTerminalRuleCall_0() { return cValueWORTTerminalRuleCall_0; }
	}
	
	
	private final ModelElements pModel;
	private final User_Story_UmElements pUser_Story_Um;
	private final TitelElements pTitel;
	private final TextElements pText;
	private final NutzenElements pNutzen;
	private final ZuBlockElements pZuBlock;
	private final RolleElements pRolle;
	private final ZielElements pZiel;
	private final SubstantivElements pSubstantiv;
	private final InfinitElements pInfinit;
	private final TerminalRule tWORT;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BelegGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pUser_Story_Um = new User_Story_UmElements();
		this.pTitel = new TitelElements();
		this.pText = new TextElements();
		this.pNutzen = new NutzenElements();
		this.pZuBlock = new ZuBlockElements();
		this.pRolle = new RolleElements();
		this.pZiel = new ZielElements();
		this.pSubstantiv = new SubstantivElements();
		this.pInfinit = new InfinitElements();
		this.tWORT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.WORT");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.htwdd.sf.beleg.s86320.s86372.Beleg".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    story+=User_Story_Um*
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	////Null testen:
	////Als Bearbeiter möchte ich Anträge einsehen, um Projekte zu bezuschussen.
	////
	////Eins testen:
	////Als Bearbeiter möchte ich Pdf exportieren, um Dokumente zuückzusenden.
	////
	////Zwei testen:
	////Als Bearbeiter möchte ich Dokumente kommentieren, um Anmerkungen hinzuzufügen.
	////
	////Drei testen:
	////Als Bediener möchte ich Roboter steuern, um Kabel zurechtzuzupfen.
	////
	////Vier testen:
	////Um Projekte zu bezuschussen, möchte ich als Bearbeiter Anträge einsehen.
	////
	////Fünf testen:
	////Um Dokumente zurückzusenden, möchte ich als Bearbeiter Dateien exportieren.
	////
	////Sechs testen:
	////Um Anmerkungen hinzuzufügen, möchte ich als Bearbeiter Dokumente kommentieren.
	////
	////Sieben testen:
	////Um Kabel zurechtzuzupfen, möchte ich als Bediener Roboter steuern.
	//// <Titel>: Um <Nutzen>, möchte ich als <Rolle> <Ziel/Wunsch>.
	//User_Story_Um:
	//    title=Titel ':'
	//    'Um' use=Nutzen ','
	//    'möchte' 'ich' 'als'
	//    role=Rolle
	//    goal=Ziel
	//    '.'
	//;
	public User_Story_UmElements getUser_Story_UmAccess() {
		return pUser_Story_Um;
	}
	
	public ParserRule getUser_Story_UmRule() {
		return getUser_Story_UmAccess().getRule();
	}
	
	//Titel:
	//    textpart += Text+
	////    subst=Substantiv
	////    infinit += Infinit+
	//;
	public TitelElements getTitelAccess() {
		return pTitel;
	}
	
	public ParserRule getTitelRule() {
		return getTitelAccess().getRule();
	}
	
	//Text:
	//    value = WORT
	//;
	public TextElements getTextAccess() {
		return pText;
	}
	
	public ParserRule getTextRule() {
		return getTextAccess().getRule();
	}
	
	//Nutzen:
	//    subst = Substantiv
	//    zuBlock=ZuBlock?
	//    infinit += Infinit+
	//;
	public NutzenElements getNutzenAccess() {
		return pNutzen;
	}
	
	public ParserRule getNutzenRule() {
		return getNutzenAccess().getRule();
	}
	
	//ZuBlock:
	//    'zu'
	//;
	public ZuBlockElements getZuBlockAccess() {
		return pZuBlock;
	}
	
	public ParserRule getZuBlockRule() {
		return getZuBlockAccess().getRule();
	}
	
	//Rolle:
	//    subst = Substantiv
	//;
	public RolleElements getRolleAccess() {
		return pRolle;
	}
	
	public ParserRule getRolleRule() {
		return getRolleAccess().getRule();
	}
	
	//Ziel:
	//    subst = Substantiv
	//    infinit += Infinit+
	//;
	public ZielElements getZielAccess() {
		return pZiel;
	}
	
	public ParserRule getZielRule() {
		return getZielAccess().getRule();
	}
	
	//Substantiv:
	//    value = WORT
	//;
	public SubstantivElements getSubstantivAccess() {
		return pSubstantiv;
	}
	
	public ParserRule getSubstantivRule() {
		return getSubstantivAccess().getRule();
	}
	
	//Infinit:
	//    value = WORT
	//;
	public InfinitElements getInfinitAccess() {
		return pInfinit;
	}
	
	public ParserRule getInfinitRule() {
		return getInfinitAccess().getRule();
	}
	
	//terminal WORT:
	//     ('a'..'z' | 'A'..'Z' | 'Ä' | 'Ö' | 'Ü' | 'ä' | 'ö' | 'ü' | 'ß')+
	//;
	public TerminalRule getWORTRule() {
		return tWORT;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
