/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BelegGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Model");
		private final Assignment cStoryAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStorySParserRuleCall_0 = (RuleCall)cStoryAssignment.eContents().get(0);
		
		//Model:
		//    story+=S*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//story+=S*
		public Assignment getStoryAssignment() { return cStoryAssignment; }
		
		//S
		public RuleCall getStorySParserRuleCall_0() { return cStorySParserRuleCall_0; }
	}
	public class StoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Story");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTitleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTitleIDTerminalRuleCall_0_0 = (RuleCall)cTitleAssignment_0.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleIDTerminalRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cUmKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUseAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUseIDTerminalRuleCall_4_0 = (RuleCall)cUseAssignment_4.eContents().get(0);
		private final Assignment cUseAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cUseIDTerminalRuleCall_5_0 = (RuleCall)cUseAssignment_5.eContents().get(0);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cMöchteKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cIchKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cAlsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cRoleAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cRoleIDTerminalRuleCall_10_0 = (RuleCall)cRoleAssignment_10.eContents().get(0);
		private final Assignment cGoalAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cGoalIDTerminalRuleCall_11_0 = (RuleCall)cGoalAssignment_11.eContents().get(0);
		private final Assignment cGoalAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cGoalIDTerminalRuleCall_12_0 = (RuleCall)cGoalAssignment_12.eContents().get(0);
		private final Keyword cFullStopKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Story:
		//    title+=ID (title+=ID)*
		//    ':' 'Um'
		//    use+=ID (use+=ID)*
		//    ','    'möchte' 'ich' 'als'
		//    role=ID
		//    goal+=ID (goal+=ID)*
		//    '.'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//title+=ID (title+=ID)*
		//':' 'Um'
		//use+=ID (use+=ID)*
		//','    'möchte' 'ich' 'als'
		//role=ID
		//goal+=ID (goal+=ID)*
		//'.'
		public Group getGroup() { return cGroup; }
		
		//title+=ID
		public Assignment getTitleAssignment_0() { return cTitleAssignment_0; }
		
		//ID
		public RuleCall getTitleIDTerminalRuleCall_0_0() { return cTitleIDTerminalRuleCall_0_0; }
		
		//(title+=ID)*
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }
		
		//ID
		public RuleCall getTitleIDTerminalRuleCall_1_0() { return cTitleIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'Um'
		public Keyword getUmKeyword_3() { return cUmKeyword_3; }
		
		//use+=ID
		public Assignment getUseAssignment_4() { return cUseAssignment_4; }
		
		//ID
		public RuleCall getUseIDTerminalRuleCall_4_0() { return cUseIDTerminalRuleCall_4_0; }
		
		//(use+=ID)*
		public Assignment getUseAssignment_5() { return cUseAssignment_5; }
		
		//ID
		public RuleCall getUseIDTerminalRuleCall_5_0() { return cUseIDTerminalRuleCall_5_0; }
		
		//','
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
		
		//'möchte'
		public Keyword getMöchteKeyword_7() { return cMöchteKeyword_7; }
		
		//'ich'
		public Keyword getIchKeyword_8() { return cIchKeyword_8; }
		
		//'als'
		public Keyword getAlsKeyword_9() { return cAlsKeyword_9; }
		
		//role=ID
		public Assignment getRoleAssignment_10() { return cRoleAssignment_10; }
		
		//ID
		public RuleCall getRoleIDTerminalRuleCall_10_0() { return cRoleIDTerminalRuleCall_10_0; }
		
		//goal+=ID
		public Assignment getGoalAssignment_11() { return cGoalAssignment_11; }
		
		//ID
		public RuleCall getGoalIDTerminalRuleCall_11_0() { return cGoalIDTerminalRuleCall_11_0; }
		
		//(goal+=ID)*
		public Assignment getGoalAssignment_12() { return cGoalAssignment_12; }
		
		//ID
		public RuleCall getGoalIDTerminalRuleCall_12_0() { return cGoalIDTerminalRuleCall_12_0; }
		
		//'.'
		public Keyword getFullStopKeyword_13() { return cFullStopKeyword_13; }
	}
	public class SElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.S");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cXeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cXeXPartParserRuleCall_0_0 = (RuleCall)cXeAssignment_0.eContents().get(0);
		private final Assignment cYeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cYeYPartParserRuleCall_1_0 = (RuleCall)cYeAssignment_1.eContents().get(0);
		private final Assignment cZeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cZeZPartParserRuleCall_2_0 = (RuleCall)cZeAssignment_2.eContents().get(0);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//S: xe=XPart ye=YPart ze=ZPart '.';
		@Override public ParserRule getRule() { return rule; }
		
		//xe=XPart ye=YPart ze=ZPart '.'
		public Group getGroup() { return cGroup; }
		
		//xe=XPart
		public Assignment getXeAssignment_0() { return cXeAssignment_0; }
		
		//XPart
		public RuleCall getXeXPartParserRuleCall_0_0() { return cXeXPartParserRuleCall_0_0; }
		
		//ye=YPart
		public Assignment getYeAssignment_1() { return cYeAssignment_1; }
		
		//YPart
		public RuleCall getYeYPartParserRuleCall_1_0() { return cYeYPartParserRuleCall_1_0; }
		
		//ze=ZPart
		public Assignment getZeAssignment_2() { return cZeAssignment_2; }
		
		//ZPart
		public RuleCall getZeZPartParserRuleCall_2_0() { return cZeZPartParserRuleCall_2_0; }
		
		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
	}
	public class XPartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.XPart");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTiAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTiTitleParserRuleCall_0_0 = (RuleCall)cTiAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cUmKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//XPart: ti=Title ':' 'Um';
		@Override public ParserRule getRule() { return rule; }
		
		//ti=Title ':' 'Um'
		public Group getGroup() { return cGroup; }
		
		//ti=Title
		public Assignment getTiAssignment_0() { return cTiAssignment_0; }
		
		//Title
		public RuleCall getTiTitleParserRuleCall_0_0() { return cTiTitleParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//'Um'
		public Keyword getUmKeyword_2() { return cUmKeyword_2; }
	}
	public class TitleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Title");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTitelAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTitelIDTerminalRuleCall_0_0 = (RuleCall)cTitelAssignment_0.eContents().get(0);
		private final Assignment cTitelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitelIDTerminalRuleCall_1_0 = (RuleCall)cTitelAssignment_1.eContents().get(0);
		
		//Title: Titel+=ID (Titel+=ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//Titel+=ID (Titel+=ID)*
		public Group getGroup() { return cGroup; }
		
		//Titel+=ID
		public Assignment getTitelAssignment_0() { return cTitelAssignment_0; }
		
		//ID
		public RuleCall getTitelIDTerminalRuleCall_0_0() { return cTitelIDTerminalRuleCall_0_0; }
		
		//(Titel+=ID)*
		public Assignment getTitelAssignment_1() { return cTitelAssignment_1; }
		
		//ID
		public RuleCall getTitelIDTerminalRuleCall_1_0() { return cTitelIDTerminalRuleCall_1_0; }
	}
	public class YPartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.YPart");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cUsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cUsUseParserRuleCall_0_0 = (RuleCall)cUsAssignment_0.eContents().get(0);
		private final Keyword cCommaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cMöchteKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cIchKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cAlsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//YPart: us=Use ',' 'möchte' 'ich' 'als';
		@Override public ParserRule getRule() { return rule; }
		
		//us=Use ',' 'möchte' 'ich' 'als'
		public Group getGroup() { return cGroup; }
		
		//us=Use
		public Assignment getUsAssignment_0() { return cUsAssignment_0; }
		
		//Use
		public RuleCall getUsUseParserRuleCall_0_0() { return cUsUseParserRuleCall_0_0; }
		
		//','
		public Keyword getCommaKeyword_1() { return cCommaKeyword_1; }
		
		//'möchte'
		public Keyword getMöchteKeyword_2() { return cMöchteKeyword_2; }
		
		//'ich'
		public Keyword getIchKeyword_3() { return cIchKeyword_3; }
		
		//'als'
		public Keyword getAlsKeyword_4() { return cAlsKeyword_4; }
	}
	public class UseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Use");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNutzenAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNutzenIDTerminalRuleCall_0_0 = (RuleCall)cNutzenAssignment_0.eContents().get(0);
		private final Assignment cNutzenAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNutzenIDTerminalRuleCall_1_0 = (RuleCall)cNutzenAssignment_1.eContents().get(0);
		
		//Use: Nutzen+=ID (Nutzen+=ID)* ;
		@Override public ParserRule getRule() { return rule; }
		
		//Nutzen+=ID (Nutzen+=ID)*
		public Group getGroup() { return cGroup; }
		
		//Nutzen+=ID
		public Assignment getNutzenAssignment_0() { return cNutzenAssignment_0; }
		
		//ID
		public RuleCall getNutzenIDTerminalRuleCall_0_0() { return cNutzenIDTerminalRuleCall_0_0; }
		
		//(Nutzen+=ID)*
		public Assignment getNutzenAssignment_1() { return cNutzenAssignment_1; }
		
		//ID
		public RuleCall getNutzenIDTerminalRuleCall_1_0() { return cNutzenIDTerminalRuleCall_1_0; }
	}
	public class ZPartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.ZPart");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRolleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cRolleIDTerminalRuleCall_0_0 = (RuleCall)cRolleAssignment_0.eContents().get(0);
		private final Assignment cGoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cGoGoalParserRuleCall_1_0 = (RuleCall)cGoAssignment_1.eContents().get(0);
		
		//ZPart: Rolle=ID go=Goal;
		@Override public ParserRule getRule() { return rule; }
		
		//Rolle=ID go=Goal
		public Group getGroup() { return cGroup; }
		
		//Rolle=ID
		public Assignment getRolleAssignment_0() { return cRolleAssignment_0; }
		
		//ID
		public RuleCall getRolleIDTerminalRuleCall_0_0() { return cRolleIDTerminalRuleCall_0_0; }
		
		//go=Goal
		public Assignment getGoAssignment_1() { return cGoAssignment_1; }
		
		//Goal
		public RuleCall getGoGoalParserRuleCall_1_0() { return cGoGoalParserRuleCall_1_0; }
	}
	public class GoalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwdd.sf.beleg.s86320.s86372.Beleg.Goal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cZielAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cZielIDTerminalRuleCall_0_0 = (RuleCall)cZielAssignment_0.eContents().get(0);
		private final Assignment cZielAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cZielIDTerminalRuleCall_1_0 = (RuleCall)cZielAssignment_1.eContents().get(0);
		
		//Goal: Ziel+=ID (Ziel+=ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//Ziel+=ID (Ziel+=ID)*
		public Group getGroup() { return cGroup; }
		
		//Ziel+=ID
		public Assignment getZielAssignment_0() { return cZielAssignment_0; }
		
		//ID
		public RuleCall getZielIDTerminalRuleCall_0_0() { return cZielIDTerminalRuleCall_0_0; }
		
		//(Ziel+=ID)*
		public Assignment getZielAssignment_1() { return cZielAssignment_1; }
		
		//ID
		public RuleCall getZielIDTerminalRuleCall_1_0() { return cZielIDTerminalRuleCall_1_0; }
	}
	
	
	private final ModelElements pModel;
	private final StoryElements pStory;
	private final SElements pS;
	private final XPartElements pXPart;
	private final TitleElements pTitle;
	private final YPartElements pYPart;
	private final UseElements pUse;
	private final ZPartElements pZPart;
	private final GoalElements pGoal;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BelegGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pStory = new StoryElements();
		this.pS = new SElements();
		this.pXPart = new XPartElements();
		this.pTitle = new TitleElements();
		this.pYPart = new YPartElements();
		this.pUse = new UseElements();
		this.pZPart = new ZPartElements();
		this.pGoal = new GoalElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.htwdd.sf.beleg.s86320.s86372.Beleg".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    story+=S*
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Story:
	//    title+=ID (title+=ID)*
	//    ':' 'Um'
	//    use+=ID (use+=ID)*
	//    ','    'möchte' 'ich' 'als'
	//    role=ID
	//    goal+=ID (goal+=ID)*
	//    '.'
	//;
	public StoryElements getStoryAccess() {
		return pStory;
	}
	
	public ParserRule getStoryRule() {
		return getStoryAccess().getRule();
	}
	
	//S: xe=XPart ye=YPart ze=ZPart '.';
	public SElements getSAccess() {
		return pS;
	}
	
	public ParserRule getSRule() {
		return getSAccess().getRule();
	}
	
	//XPart: ti=Title ':' 'Um';
	public XPartElements getXPartAccess() {
		return pXPart;
	}
	
	public ParserRule getXPartRule() {
		return getXPartAccess().getRule();
	}
	
	//Title: Titel+=ID (Titel+=ID)*;
	public TitleElements getTitleAccess() {
		return pTitle;
	}
	
	public ParserRule getTitleRule() {
		return getTitleAccess().getRule();
	}
	
	//YPart: us=Use ',' 'möchte' 'ich' 'als';
	public YPartElements getYPartAccess() {
		return pYPart;
	}
	
	public ParserRule getYPartRule() {
		return getYPartAccess().getRule();
	}
	
	//Use: Nutzen+=ID (Nutzen+=ID)* ;
	public UseElements getUseAccess() {
		return pUse;
	}
	
	public ParserRule getUseRule() {
		return getUseAccess().getRule();
	}
	
	//ZPart: Rolle=ID go=Goal;
	public ZPartElements getZPartAccess() {
		return pZPart;
	}
	
	public ParserRule getZPartRule() {
		return getZPartAccess().getRule();
	}
	
	//Goal: Ziel+=ID (Ziel+=ID)*;
	public GoalElements getGoalAccess() {
		return pGoal;
	}
	
	public ParserRule getGoalRule() {
		return getGoalAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
