/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.ui.labeling;

import com.google.inject.Inject;

import de.htwdd.sf.beleg.s86320s86372.beleg.Model;
import de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen;
import de.htwdd.sf.beleg.s86320s86372.beleg.Rolle;
import de.htwdd.sf.beleg.s86320s86372.beleg.Titel;
import de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um;
import de.htwdd.sf.beleg.s86320s86372.beleg.Ziel;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class BelegLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public BelegLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	// Labels and icons can be computed like this:
	
//	String text(Greeting ele) {
//		return "A greeting to " + ele.getName();
//	}
//
//	String image(Greeting ele) {
//		return "Greeting.gif";
//	}
	
	// Knoten Label
	String text(User_Story_Um story) {
		
		if (story.eContainer() instanceof Model model) {
			int index = model.getStory().indexOf(story);
			return "User Story Um " + (index + 1);
		}
		
		return "User Story Um";
	}
	
	String text(Titel t) {
		return "Titel";
	}
	
	String text(Nutzen n) {
		return "Nutzen";
	}
	String text(Rolle r) {
		return "Rolle";
	}
	
	String text(Ziel z) {
		return "Ziel/Wunsch";
	}
	
}


