/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.htwdd.sf.beleg.s86320s86372.ide.contentassist.antlr.internal.InternalBelegParser;
import de.htwdd.sf.beleg.s86320s86372.services.BelegGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class BelegParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(BelegGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, BelegGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getUser_Story_UmAccess().getGroup(), "rule__User_Story_Um__Group__0");
			builder.put(grammarAccess.getNutzenAccess().getGroup(), "rule__Nutzen__Group__0");
			builder.put(grammarAccess.getZielAccess().getGroup(), "rule__Ziel__Group__0");
			builder.put(grammarAccess.getModelAccess().getStoryAssignment(), "rule__Model__StoryAssignment");
			builder.put(grammarAccess.getUser_Story_UmAccess().getTitleAssignment_0(), "rule__User_Story_Um__TitleAssignment_0");
			builder.put(grammarAccess.getUser_Story_UmAccess().getDoppelpunktAssignment_1(), "rule__User_Story_Um__DoppelpunktAssignment_1");
			builder.put(grammarAccess.getUser_Story_UmAccess().getUmAssignment_2(), "rule__User_Story_Um__UmAssignment_2");
			builder.put(grammarAccess.getUser_Story_UmAccess().getUseAssignment_3(), "rule__User_Story_Um__UseAssignment_3");
			builder.put(grammarAccess.getUser_Story_UmAccess().getKommaAssignment_4(), "rule__User_Story_Um__KommaAssignment_4");
			builder.put(grammarAccess.getUser_Story_UmAccess().getMoechteAssignment_5(), "rule__User_Story_Um__MoechteAssignment_5");
			builder.put(grammarAccess.getUser_Story_UmAccess().getIchAssignment_6(), "rule__User_Story_Um__IchAssignment_6");
			builder.put(grammarAccess.getUser_Story_UmAccess().getAlsAssignment_7(), "rule__User_Story_Um__AlsAssignment_7");
			builder.put(grammarAccess.getUser_Story_UmAccess().getRoleAssignment_8(), "rule__User_Story_Um__RoleAssignment_8");
			builder.put(grammarAccess.getUser_Story_UmAccess().getGoalAssignment_9(), "rule__User_Story_Um__GoalAssignment_9");
			builder.put(grammarAccess.getUser_Story_UmAccess().getPunktAssignment_10(), "rule__User_Story_Um__PunktAssignment_10");
			builder.put(grammarAccess.getTitelAccess().getTextpartAssignment(), "rule__Titel__TextpartAssignment");
			builder.put(grammarAccess.getTextAccess().getValueAssignment(), "rule__Text__ValueAssignment");
			builder.put(grammarAccess.getNutzenAccess().getSubstAssignment_0(), "rule__Nutzen__SubstAssignment_0");
			builder.put(grammarAccess.getNutzenAccess().getZuAssignment_1(), "rule__Nutzen__ZuAssignment_1");
			builder.put(grammarAccess.getNutzenAccess().getInfinitAssignment_2(), "rule__Nutzen__InfinitAssignment_2");
			builder.put(grammarAccess.getRolleAccess().getSubstAssignment(), "rule__Rolle__SubstAssignment");
			builder.put(grammarAccess.getZielAccess().getSubstAssignment_0(), "rule__Ziel__SubstAssignment_0");
			builder.put(grammarAccess.getZielAccess().getInfinitAssignment_1(), "rule__Ziel__InfinitAssignment_1");
			builder.put(grammarAccess.getDoppelPunktBlockAccess().getValueAssignment(), "rule__DoppelPunktBlock__ValueAssignment");
			builder.put(grammarAccess.getUmBlockAccess().getValueAssignment(), "rule__UmBlock__ValueAssignment");
			builder.put(grammarAccess.getKommaBlockAccess().getValueAssignment(), "rule__KommaBlock__ValueAssignment");
			builder.put(grammarAccess.getZuBlockAccess().getValueAssignment(), "rule__ZuBlock__ValueAssignment");
			builder.put(grammarAccess.getMoechteBlockAccess().getValueAssignment(), "rule__MoechteBlock__ValueAssignment");
			builder.put(grammarAccess.getIchBlockAccess().getValueAssignment(), "rule__IchBlock__ValueAssignment");
			builder.put(grammarAccess.getAlsBlockAccess().getValueAssignment(), "rule__AlsBlock__ValueAssignment");
			builder.put(grammarAccess.getPunktBlockAccess().getValueAssignment(), "rule__PunktBlock__ValueAssignment");
			builder.put(grammarAccess.getSubstantivAccess().getValueAssignment(), "rule__Substantiv__ValueAssignment");
			builder.put(grammarAccess.getInfinitAccess().getValueAssignment(), "rule__Infinit__ValueAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private BelegGrammarAccess grammarAccess;

	@Override
	protected InternalBelegParser createParser() {
		InternalBelegParser result = new InternalBelegParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BelegGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BelegGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
