/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.beleg.impl;

import de.htwdd.sf.beleg.s86320.s86372.beleg.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BelegFactoryImpl extends EFactoryImpl implements BelegFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static BelegFactory init()
  {
    try
    {
      BelegFactory theBelegFactory = (BelegFactory)EPackage.Registry.INSTANCE.getEFactory(BelegPackage.eNS_URI);
      if (theBelegFactory != null)
      {
        return theBelegFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new BelegFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BelegFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case BelegPackage.MODEL: return createModel();
      case BelegPackage.USER_STORY_UM: return createUser_Story_Um();
      case BelegPackage.TITEL: return createTitel();
      case BelegPackage.TEXT: return createText();
      case BelegPackage.NUTZEN: return createNutzen();
      case BelegPackage.ROLLE: return createRolle();
      case BelegPackage.ZIEL: return createZiel();
      case BelegPackage.SUBSTANTIV: return createSubstantiv();
      case BelegPackage.INFINIT: return createInfinit();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public User_Story_Um createUser_Story_Um()
  {
    User_Story_UmImpl user_Story_Um = new User_Story_UmImpl();
    return user_Story_Um;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Titel createTitel()
  {
    TitelImpl titel = new TitelImpl();
    return titel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Text createText()
  {
    TextImpl text = new TextImpl();
    return text;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nutzen createNutzen()
  {
    NutzenImpl nutzen = new NutzenImpl();
    return nutzen;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rolle createRolle()
  {
    RolleImpl rolle = new RolleImpl();
    return rolle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ziel createZiel()
  {
    ZielImpl ziel = new ZielImpl();
    return ziel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Substantiv createSubstantiv()
  {
    SubstantivImpl substantiv = new SubstantivImpl();
    return substantiv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Infinit createInfinit()
  {
    InfinitImpl infinit = new InfinitImpl();
    return infinit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BelegPackage getBelegPackage()
  {
    return (BelegPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static BelegPackage getPackage()
  {
    return BelegPackage.eINSTANCE;
  }

} //BelegFactoryImpl
