/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372.beleg.impl;

import de.htwdd.sf.beleg.s86320.s86372.beleg.BelegPackage;
import de.htwdd.sf.beleg.s86320.s86372.beleg.Title;
import de.htwdd.sf.beleg.s86320.s86372.beleg.XPart;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XPart</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320.s86372.beleg.impl.XPartImpl#getTi <em>Ti</em>}</li>
 * </ul>
 *
 * @generated
 */
public class XPartImpl extends MinimalEObjectImpl.Container implements XPart
{
  /**
   * The cached value of the '{@link #getTi() <em>Ti</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTi()
   * @generated
   * @ordered
   */
  protected Title ti;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XPartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BelegPackage.Literals.XPART;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Title getTi()
  {
    return ti;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTi(Title newTi, NotificationChain msgs)
  {
    Title oldTi = ti;
    ti = newTi;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BelegPackage.XPART__TI, oldTi, newTi);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTi(Title newTi)
  {
    if (newTi != ti)
    {
      NotificationChain msgs = null;
      if (ti != null)
        msgs = ((InternalEObject)ti).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BelegPackage.XPART__TI, null, msgs);
      if (newTi != null)
        msgs = ((InternalEObject)newTi).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BelegPackage.XPART__TI, null, msgs);
      msgs = basicSetTi(newTi, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BelegPackage.XPART__TI, newTi, newTi));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BelegPackage.XPART__TI:
        return basicSetTi(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BelegPackage.XPART__TI:
        return getTi();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BelegPackage.XPART__TI:
        setTi((Title)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BelegPackage.XPART__TI:
        setTi((Title)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BelegPackage.XPART__TI:
        return ti != null;
    }
    return super.eIsSet(featureID);
  }

} //XPartImpl
