/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.generator;

import de.htwdd.sf.beleg.s86320s86372.beleg.Infinit;
import de.htwdd.sf.beleg.s86320s86372.beleg.Model;
import de.htwdd.sf.beleg.s86320s86372.beleg.Text;
import de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;

@SuppressWarnings("all")
public class BelegGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _get = resource.getContents().get(0);
    final Model model = ((Model) _get);
    final StringBuilder csv = new StringBuilder();
    csv.append("Titel,Nutzen,Ziel,Rolle\n");
    EList<User_Story_Um> _story = model.getStory();
    for (final User_Story_Um story : _story) {
      {
        final Function1<Text, String> _function = (Text it) -> {
          return it.getValue();
        };
        csv.append(IterableExtensions.join(ListExtensions.<Text, String>map(story.getTitle().getTextpart(), _function), " "));
        csv.append(",");
        String _value = story.getUse().getSubst().getValue();
        String _plus = (_value + " ");
        final Function1<Infinit, String> _function_1 = (Infinit it) -> {
          return it.getValue();
        };
        String _join = IterableExtensions.join(ListExtensions.<Infinit, String>map(story.getUse().getInfinit(), _function_1), " ");
        String _plus_1 = (_plus + _join);
        csv.append(_plus_1);
        csv.append(",");
        csv.append(story.getRole().getSubst().getValue());
        csv.append(",");
        String _value_1 = story.getGoal().getSubst().getValue();
        String _plus_2 = (_value_1 + " ");
        final Function1<Infinit, String> _function_2 = (Infinit it) -> {
          return it.getValue();
        };
        String _join_1 = IterableExtensions.join(ListExtensions.<Infinit, String>map(story.getGoal().getInfinit(), _function_2), " ");
        String _plus_3 = (_plus_2 + _join_1);
        csv.append(_plus_3);
        csv.append("\n");
      }
    }
    fsa.generateFile("s86320s86372.csv", csv.toString());
  }
}
