/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.htwdd.sf.beleg.s86320s86372.BelegRuntimeModule;
import de.htwdd.sf.beleg.s86320s86372.BelegStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BelegIdeSetup extends BelegStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BelegRuntimeModule(), new BelegIdeModule()));
	}
	
}
