/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320.s86372;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BelegRuntimeModule extends AbstractBelegRuntimeModule {
}
