/*
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.ui.outline;

import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import de.htwdd.sf.beleg.s86320s86372.beleg.Infinit;
import de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen;
import de.htwdd.sf.beleg.s86320s86372.beleg.Rolle;
import de.htwdd.sf.beleg.s86320s86372.beleg.Text;
import de.htwdd.sf.beleg.s86320s86372.beleg.Titel;
import de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um;
import de.htwdd.sf.beleg.s86320s86372.beleg.Ziel;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class BelegOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
	// Aufbau Baumstruktur
	
	// User Story
	protected void _children(User_Story_Um obj, IOutlineNode parent) {
		createNode(parent, obj.getTitle());
		createNode(parent, obj.getUse());
		createNode(parent, obj.getRole());
		createNode(parent, obj.getGoal());
	}
	
	// <Titel>
	protected void _children(Titel obj, IOutlineNode parent) {
		for (Text t : obj.getTextpart()) {
			createNode(parent, t);
		}
	}
	
	// <Nutzen>
	protected void _children(Nutzen obj, IOutlineNode parent) {
		createNode(parent, obj.getSubst());
		
		if (obj.getZu() != null) {
			createNode(parent, obj.getZu());
		}
		
		for (Infinit i : obj.getInfinit()) {
			createNode(parent, i);
		}
	}
	
	// <Rolle>
	protected void _children(Rolle obj, IOutlineNode parent) {
		createNode(parent, obj.getSubst());
	}
	
	// <Ziel>
	protected void _children(Ziel obj, IOutlineNode parent) {
		createNode(parent,obj.getSubst());
		
		for (Infinit i : obj.getInfinit()) {
			createNode(parent, i);
		}
	}
		
}

