/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.beleg;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegFactory
 * @model kind="package"
 * @generated
 */
public interface BelegPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "beleg";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.htwdd.de/sf/beleg/s86320s86372/Beleg";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "beleg";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BelegPackage eINSTANCE = de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl.init();

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.ModelImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Story</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STORY = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.User_Story_UmImpl <em>User Story Um</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.User_Story_UmImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getUser_Story_Um()
   * @generated
   */
  int USER_STORY_UM = 1;

  /**
   * The feature id for the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__TITLE = 0;

  /**
   * The feature id for the '<em><b>Doppelpunkt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__DOPPELPUNKT = 1;

  /**
   * The feature id for the '<em><b>Um</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__UM = 2;

  /**
   * The feature id for the '<em><b>Use</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__USE = 3;

  /**
   * The feature id for the '<em><b>Komma</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__KOMMA = 4;

  /**
   * The feature id for the '<em><b>Moechte</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__MOECHTE = 5;

  /**
   * The feature id for the '<em><b>Ich</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__ICH = 6;

  /**
   * The feature id for the '<em><b>Als</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__ALS = 7;

  /**
   * The feature id for the '<em><b>Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__ROLE = 8;

  /**
   * The feature id for the '<em><b>Goal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__GOAL = 9;

  /**
   * The feature id for the '<em><b>Punkt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM__PUNKT = 10;

  /**
   * The number of structural features of the '<em>User Story Um</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_STORY_UM_FEATURE_COUNT = 11;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.TitelImpl <em>Titel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.TitelImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getTitel()
   * @generated
   */
  int TITEL = 2;

  /**
   * The feature id for the '<em><b>Textpart</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITEL__TEXTPART = 0;

  /**
   * The number of structural features of the '<em>Titel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.TextImpl <em>Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.TextImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getText()
   * @generated
   */
  int TEXT = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.NutzenImpl <em>Nutzen</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.NutzenImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getNutzen()
   * @generated
   */
  int NUTZEN = 4;

  /**
   * The feature id for the '<em><b>Subst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN__SUBST = 0;

  /**
   * The feature id for the '<em><b>Zu</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN__ZU = 1;

  /**
   * The feature id for the '<em><b>Infinit</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN__INFINIT = 2;

  /**
   * The number of structural features of the '<em>Nutzen</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.RolleImpl <em>Rolle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.RolleImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getRolle()
   * @generated
   */
  int ROLLE = 5;

  /**
   * The feature id for the '<em><b>Subst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLLE__SUBST = 0;

  /**
   * The number of structural features of the '<em>Rolle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.ZielImpl <em>Ziel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.ZielImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getZiel()
   * @generated
   */
  int ZIEL = 6;

  /**
   * The feature id for the '<em><b>Subst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZIEL__SUBST = 0;

  /**
   * The feature id for the '<em><b>Infinit</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZIEL__INFINIT = 1;

  /**
   * The number of structural features of the '<em>Ziel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZIEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.DoppelPunktBlockImpl <em>Doppel Punkt Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.DoppelPunktBlockImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getDoppelPunktBlock()
   * @generated
   */
  int DOPPEL_PUNKT_BLOCK = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOPPEL_PUNKT_BLOCK__VALUE = 0;

  /**
   * The number of structural features of the '<em>Doppel Punkt Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOPPEL_PUNKT_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.UmBlockImpl <em>Um Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.UmBlockImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getUmBlock()
   * @generated
   */
  int UM_BLOCK = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UM_BLOCK__VALUE = 0;

  /**
   * The number of structural features of the '<em>Um Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UM_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.KommaBlockImpl <em>Komma Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.KommaBlockImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getKommaBlock()
   * @generated
   */
  int KOMMA_BLOCK = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KOMMA_BLOCK__VALUE = 0;

  /**
   * The number of structural features of the '<em>Komma Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KOMMA_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.ZuBlockImpl <em>Zu Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.ZuBlockImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getZuBlock()
   * @generated
   */
  int ZU_BLOCK = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZU_BLOCK__VALUE = 0;

  /**
   * The number of structural features of the '<em>Zu Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZU_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.MoechteBlockImpl <em>Moechte Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.MoechteBlockImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getMoechteBlock()
   * @generated
   */
  int MOECHTE_BLOCK = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOECHTE_BLOCK__VALUE = 0;

  /**
   * The number of structural features of the '<em>Moechte Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOECHTE_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.IchBlockImpl <em>Ich Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.IchBlockImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getIchBlock()
   * @generated
   */
  int ICH_BLOCK = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ICH_BLOCK__VALUE = 0;

  /**
   * The number of structural features of the '<em>Ich Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ICH_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.AlsBlockImpl <em>Als Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.AlsBlockImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getAlsBlock()
   * @generated
   */
  int ALS_BLOCK = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALS_BLOCK__VALUE = 0;

  /**
   * The number of structural features of the '<em>Als Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALS_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.PunktBlockImpl <em>Punkt Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.PunktBlockImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getPunktBlock()
   * @generated
   */
  int PUNKT_BLOCK = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUNKT_BLOCK__VALUE = 0;

  /**
   * The number of structural features of the '<em>Punkt Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUNKT_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.SubstantivImpl <em>Substantiv</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.SubstantivImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getSubstantiv()
   * @generated
   */
  int SUBSTANTIV = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSTANTIV__VALUE = 0;

  /**
   * The number of structural features of the '<em>Substantiv</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSTANTIV_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.InfinitImpl <em>Infinit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.InfinitImpl
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getInfinit()
   * @generated
   */
  int INFINIT = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFINIT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Infinit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFINIT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Model#getStory <em>Story</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Story</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Model#getStory()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Story();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um <em>User Story Um</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Story Um</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um
   * @generated
   */
  EClass getUser_Story_Um();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Title</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getTitle()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Title();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getDoppelpunkt <em>Doppelpunkt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Doppelpunkt</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getDoppelpunkt()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Doppelpunkt();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getUm <em>Um</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Um</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getUm()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Um();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getUse <em>Use</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Use</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getUse()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Use();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getKomma <em>Komma</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Komma</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getKomma()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Komma();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getMoechte <em>Moechte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Moechte</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getMoechte()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Moechte();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getIch <em>Ich</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ich</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getIch()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Ich();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getAls <em>Als</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Als</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getAls()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Als();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Role</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getRole()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Role();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getGoal <em>Goal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Goal</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getGoal()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Goal();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getPunkt <em>Punkt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Punkt</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getPunkt()
   * @see #getUser_Story_Um()
   * @generated
   */
  EReference getUser_Story_Um_Punkt();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Titel <em>Titel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Titel</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Titel
   * @generated
   */
  EClass getTitel();

  /**
   * Returns the meta object for the containment reference list '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Titel#getTextpart <em>Textpart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Textpart</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Titel#getTextpart()
   * @see #getTitel()
   * @generated
   */
  EReference getTitel_Textpart();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Text <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Text
   * @generated
   */
  EClass getText();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Text#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Text#getValue()
   * @see #getText()
   * @generated
   */
  EAttribute getText_Value();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen <em>Nutzen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nutzen</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen
   * @generated
   */
  EClass getNutzen();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen#getSubst <em>Subst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Subst</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen#getSubst()
   * @see #getNutzen()
   * @generated
   */
  EReference getNutzen_Subst();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen#getZu <em>Zu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Zu</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen#getZu()
   * @see #getNutzen()
   * @generated
   */
  EReference getNutzen_Zu();

  /**
   * Returns the meta object for the containment reference list '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen#getInfinit <em>Infinit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Infinit</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Nutzen#getInfinit()
   * @see #getNutzen()
   * @generated
   */
  EReference getNutzen_Infinit();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Rolle <em>Rolle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rolle</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Rolle
   * @generated
   */
  EClass getRolle();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Rolle#getSubst <em>Subst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Subst</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Rolle#getSubst()
   * @see #getRolle()
   * @generated
   */
  EReference getRolle_Subst();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Ziel <em>Ziel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ziel</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Ziel
   * @generated
   */
  EClass getZiel();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Ziel#getSubst <em>Subst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Subst</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Ziel#getSubst()
   * @see #getZiel()
   * @generated
   */
  EReference getZiel_Subst();

  /**
   * Returns the meta object for the containment reference list '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Ziel#getInfinit <em>Infinit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Infinit</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Ziel#getInfinit()
   * @see #getZiel()
   * @generated
   */
  EReference getZiel_Infinit();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.DoppelPunktBlock <em>Doppel Punkt Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Doppel Punkt Block</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.DoppelPunktBlock
   * @generated
   */
  EClass getDoppelPunktBlock();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.DoppelPunktBlock#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.DoppelPunktBlock#getValue()
   * @see #getDoppelPunktBlock()
   * @generated
   */
  EAttribute getDoppelPunktBlock_Value();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.UmBlock <em>Um Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Um Block</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.UmBlock
   * @generated
   */
  EClass getUmBlock();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.UmBlock#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.UmBlock#getValue()
   * @see #getUmBlock()
   * @generated
   */
  EAttribute getUmBlock_Value();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.KommaBlock <em>Komma Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Komma Block</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.KommaBlock
   * @generated
   */
  EClass getKommaBlock();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.KommaBlock#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.KommaBlock#getValue()
   * @see #getKommaBlock()
   * @generated
   */
  EAttribute getKommaBlock_Value();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.ZuBlock <em>Zu Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Zu Block</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.ZuBlock
   * @generated
   */
  EClass getZuBlock();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.ZuBlock#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.ZuBlock#getValue()
   * @see #getZuBlock()
   * @generated
   */
  EAttribute getZuBlock_Value();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.MoechteBlock <em>Moechte Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Moechte Block</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.MoechteBlock
   * @generated
   */
  EClass getMoechteBlock();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.MoechteBlock#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.MoechteBlock#getValue()
   * @see #getMoechteBlock()
   * @generated
   */
  EAttribute getMoechteBlock_Value();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.IchBlock <em>Ich Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ich Block</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.IchBlock
   * @generated
   */
  EClass getIchBlock();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.IchBlock#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.IchBlock#getValue()
   * @see #getIchBlock()
   * @generated
   */
  EAttribute getIchBlock_Value();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.AlsBlock <em>Als Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Als Block</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.AlsBlock
   * @generated
   */
  EClass getAlsBlock();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.AlsBlock#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.AlsBlock#getValue()
   * @see #getAlsBlock()
   * @generated
   */
  EAttribute getAlsBlock_Value();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.PunktBlock <em>Punkt Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Punkt Block</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.PunktBlock
   * @generated
   */
  EClass getPunktBlock();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.PunktBlock#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.PunktBlock#getValue()
   * @see #getPunktBlock()
   * @generated
   */
  EAttribute getPunktBlock_Value();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Substantiv <em>Substantiv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Substantiv</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Substantiv
   * @generated
   */
  EClass getSubstantiv();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Substantiv#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Substantiv#getValue()
   * @see #getSubstantiv()
   * @generated
   */
  EAttribute getSubstantiv_Value();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Infinit <em>Infinit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Infinit</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Infinit
   * @generated
   */
  EClass getInfinit();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s86320s86372.beleg.Infinit#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.Infinit#getValue()
   * @see #getInfinit()
   * @generated
   */
  EAttribute getInfinit_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BelegFactory getBelegFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.ModelImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Story</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STORY = eINSTANCE.getModel_Story();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.User_Story_UmImpl <em>User Story Um</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.User_Story_UmImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getUser_Story_Um()
     * @generated
     */
    EClass USER_STORY_UM = eINSTANCE.getUser_Story_Um();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__TITLE = eINSTANCE.getUser_Story_Um_Title();

    /**
     * The meta object literal for the '<em><b>Doppelpunkt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__DOPPELPUNKT = eINSTANCE.getUser_Story_Um_Doppelpunkt();

    /**
     * The meta object literal for the '<em><b>Um</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__UM = eINSTANCE.getUser_Story_Um_Um();

    /**
     * The meta object literal for the '<em><b>Use</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__USE = eINSTANCE.getUser_Story_Um_Use();

    /**
     * The meta object literal for the '<em><b>Komma</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__KOMMA = eINSTANCE.getUser_Story_Um_Komma();

    /**
     * The meta object literal for the '<em><b>Moechte</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__MOECHTE = eINSTANCE.getUser_Story_Um_Moechte();

    /**
     * The meta object literal for the '<em><b>Ich</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__ICH = eINSTANCE.getUser_Story_Um_Ich();

    /**
     * The meta object literal for the '<em><b>Als</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__ALS = eINSTANCE.getUser_Story_Um_Als();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__ROLE = eINSTANCE.getUser_Story_Um_Role();

    /**
     * The meta object literal for the '<em><b>Goal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__GOAL = eINSTANCE.getUser_Story_Um_Goal();

    /**
     * The meta object literal for the '<em><b>Punkt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_STORY_UM__PUNKT = eINSTANCE.getUser_Story_Um_Punkt();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.TitelImpl <em>Titel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.TitelImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getTitel()
     * @generated
     */
    EClass TITEL = eINSTANCE.getTitel();

    /**
     * The meta object literal for the '<em><b>Textpart</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TITEL__TEXTPART = eINSTANCE.getTitel_Textpart();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.TextImpl <em>Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.TextImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getText()
     * @generated
     */
    EClass TEXT = eINSTANCE.getText();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT__VALUE = eINSTANCE.getText_Value();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.NutzenImpl <em>Nutzen</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.NutzenImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getNutzen()
     * @generated
     */
    EClass NUTZEN = eINSTANCE.getNutzen();

    /**
     * The meta object literal for the '<em><b>Subst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUTZEN__SUBST = eINSTANCE.getNutzen_Subst();

    /**
     * The meta object literal for the '<em><b>Zu</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUTZEN__ZU = eINSTANCE.getNutzen_Zu();

    /**
     * The meta object literal for the '<em><b>Infinit</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUTZEN__INFINIT = eINSTANCE.getNutzen_Infinit();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.RolleImpl <em>Rolle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.RolleImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getRolle()
     * @generated
     */
    EClass ROLLE = eINSTANCE.getRolle();

    /**
     * The meta object literal for the '<em><b>Subst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROLLE__SUBST = eINSTANCE.getRolle_Subst();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.ZielImpl <em>Ziel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.ZielImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getZiel()
     * @generated
     */
    EClass ZIEL = eINSTANCE.getZiel();

    /**
     * The meta object literal for the '<em><b>Subst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZIEL__SUBST = eINSTANCE.getZiel_Subst();

    /**
     * The meta object literal for the '<em><b>Infinit</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZIEL__INFINIT = eINSTANCE.getZiel_Infinit();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.DoppelPunktBlockImpl <em>Doppel Punkt Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.DoppelPunktBlockImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getDoppelPunktBlock()
     * @generated
     */
    EClass DOPPEL_PUNKT_BLOCK = eINSTANCE.getDoppelPunktBlock();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOPPEL_PUNKT_BLOCK__VALUE = eINSTANCE.getDoppelPunktBlock_Value();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.UmBlockImpl <em>Um Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.UmBlockImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getUmBlock()
     * @generated
     */
    EClass UM_BLOCK = eINSTANCE.getUmBlock();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UM_BLOCK__VALUE = eINSTANCE.getUmBlock_Value();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.KommaBlockImpl <em>Komma Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.KommaBlockImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getKommaBlock()
     * @generated
     */
    EClass KOMMA_BLOCK = eINSTANCE.getKommaBlock();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KOMMA_BLOCK__VALUE = eINSTANCE.getKommaBlock_Value();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.ZuBlockImpl <em>Zu Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.ZuBlockImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getZuBlock()
     * @generated
     */
    EClass ZU_BLOCK = eINSTANCE.getZuBlock();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZU_BLOCK__VALUE = eINSTANCE.getZuBlock_Value();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.MoechteBlockImpl <em>Moechte Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.MoechteBlockImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getMoechteBlock()
     * @generated
     */
    EClass MOECHTE_BLOCK = eINSTANCE.getMoechteBlock();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOECHTE_BLOCK__VALUE = eINSTANCE.getMoechteBlock_Value();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.IchBlockImpl <em>Ich Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.IchBlockImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getIchBlock()
     * @generated
     */
    EClass ICH_BLOCK = eINSTANCE.getIchBlock();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ICH_BLOCK__VALUE = eINSTANCE.getIchBlock_Value();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.AlsBlockImpl <em>Als Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.AlsBlockImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getAlsBlock()
     * @generated
     */
    EClass ALS_BLOCK = eINSTANCE.getAlsBlock();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALS_BLOCK__VALUE = eINSTANCE.getAlsBlock_Value();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.PunktBlockImpl <em>Punkt Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.PunktBlockImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getPunktBlock()
     * @generated
     */
    EClass PUNKT_BLOCK = eINSTANCE.getPunktBlock();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PUNKT_BLOCK__VALUE = eINSTANCE.getPunktBlock_Value();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.SubstantivImpl <em>Substantiv</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.SubstantivImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getSubstantiv()
     * @generated
     */
    EClass SUBSTANTIV = eINSTANCE.getSubstantiv();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBSTANTIV__VALUE = eINSTANCE.getSubstantiv_Value();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.impl.InfinitImpl <em>Infinit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.InfinitImpl
     * @see de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegPackageImpl#getInfinit()
     * @generated
     */
    EClass INFINIT = eINSTANCE.getInfinit();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INFINIT__VALUE = eINSTANCE.getInfinit_Value();

  }

} //BelegPackage
