/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.beleg;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage
 * @generated
 */
public interface BelegFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BelegFactory eINSTANCE = de.htwdd.sf.beleg.s86320s86372.beleg.impl.BelegFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>User Story Um</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>User Story Um</em>'.
   * @generated
   */
  User_Story_Um createUser_Story_Um();

  /**
   * Returns a new object of class '<em>Titel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Titel</em>'.
   * @generated
   */
  Titel createTitel();

  /**
   * Returns a new object of class '<em>Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text</em>'.
   * @generated
   */
  Text createText();

  /**
   * Returns a new object of class '<em>Nutzen</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nutzen</em>'.
   * @generated
   */
  Nutzen createNutzen();

  /**
   * Returns a new object of class '<em>Rolle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rolle</em>'.
   * @generated
   */
  Rolle createRolle();

  /**
   * Returns a new object of class '<em>Ziel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ziel</em>'.
   * @generated
   */
  Ziel createZiel();

  /**
   * Returns a new object of class '<em>Doppel Punkt Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Doppel Punkt Block</em>'.
   * @generated
   */
  DoppelPunktBlock createDoppelPunktBlock();

  /**
   * Returns a new object of class '<em>Um Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Um Block</em>'.
   * @generated
   */
  UmBlock createUmBlock();

  /**
   * Returns a new object of class '<em>Komma Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Komma Block</em>'.
   * @generated
   */
  KommaBlock createKommaBlock();

  /**
   * Returns a new object of class '<em>Zu Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Zu Block</em>'.
   * @generated
   */
  ZuBlock createZuBlock();

  /**
   * Returns a new object of class '<em>Moechte Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Moechte Block</em>'.
   * @generated
   */
  MoechteBlock createMoechteBlock();

  /**
   * Returns a new object of class '<em>Ich Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ich Block</em>'.
   * @generated
   */
  IchBlock createIchBlock();

  /**
   * Returns a new object of class '<em>Als Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Als Block</em>'.
   * @generated
   */
  AlsBlock createAlsBlock();

  /**
   * Returns a new object of class '<em>Punkt Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Punkt Block</em>'.
   * @generated
   */
  PunktBlock createPunktBlock();

  /**
   * Returns a new object of class '<em>Substantiv</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Substantiv</em>'.
   * @generated
   */
  Substantiv createSubstantiv();

  /**
   * Returns a new object of class '<em>Infinit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Infinit</em>'.
   * @generated
   */
  Infinit createInfinit();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BelegPackage getBelegPackage();

} //BelegFactory
