/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.beleg;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Titel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.Titel#getTextpart <em>Textpart</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getTitel()
 * @model
 * @generated
 */
public interface Titel extends EObject
{
  /**
   * Returns the value of the '<em><b>Textpart</b></em>' containment reference list.
   * The list contents are of type {@link de.htwdd.sf.beleg.s86320s86372.beleg.Text}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Textpart</em>' containment reference list.
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getTitel_Textpart()
   * @model containment="true"
   * @generated
   */
  EList<Text> getTextpart();

} // Titel
