/**
 * generated by Xtext 2.41.0
 */
package de.htwdd.sf.beleg.s86320s86372.beleg;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User Story Um</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getTitle <em>Title</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getDoppelpunkt <em>Doppelpunkt</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getUm <em>Um</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getUse <em>Use</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getKomma <em>Komma</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getMoechte <em>Moechte</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getIch <em>Ich</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getAls <em>Als</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getRole <em>Role</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getGoal <em>Goal</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getPunkt <em>Punkt</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um()
 * @model
 * @generated
 */
public interface User_Story_Um extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' containment reference.
   * @see #setTitle(Titel)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Title()
   * @model containment="true"
   * @generated
   */
  Titel getTitle();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getTitle <em>Title</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' containment reference.
   * @see #getTitle()
   * @generated
   */
  void setTitle(Titel value);

  /**
   * Returns the value of the '<em><b>Doppelpunkt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doppelpunkt</em>' containment reference.
   * @see #setDoppelpunkt(DoppelPunktBlock)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Doppelpunkt()
   * @model containment="true"
   * @generated
   */
  DoppelPunktBlock getDoppelpunkt();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getDoppelpunkt <em>Doppelpunkt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doppelpunkt</em>' containment reference.
   * @see #getDoppelpunkt()
   * @generated
   */
  void setDoppelpunkt(DoppelPunktBlock value);

  /**
   * Returns the value of the '<em><b>Um</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Um</em>' containment reference.
   * @see #setUm(UmBlock)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Um()
   * @model containment="true"
   * @generated
   */
  UmBlock getUm();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getUm <em>Um</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Um</em>' containment reference.
   * @see #getUm()
   * @generated
   */
  void setUm(UmBlock value);

  /**
   * Returns the value of the '<em><b>Use</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use</em>' containment reference.
   * @see #setUse(Nutzen)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Use()
   * @model containment="true"
   * @generated
   */
  Nutzen getUse();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getUse <em>Use</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Use</em>' containment reference.
   * @see #getUse()
   * @generated
   */
  void setUse(Nutzen value);

  /**
   * Returns the value of the '<em><b>Komma</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Komma</em>' containment reference.
   * @see #setKomma(KommaBlock)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Komma()
   * @model containment="true"
   * @generated
   */
  KommaBlock getKomma();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getKomma <em>Komma</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Komma</em>' containment reference.
   * @see #getKomma()
   * @generated
   */
  void setKomma(KommaBlock value);

  /**
   * Returns the value of the '<em><b>Moechte</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Moechte</em>' containment reference.
   * @see #setMoechte(MoechteBlock)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Moechte()
   * @model containment="true"
   * @generated
   */
  MoechteBlock getMoechte();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getMoechte <em>Moechte</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Moechte</em>' containment reference.
   * @see #getMoechte()
   * @generated
   */
  void setMoechte(MoechteBlock value);

  /**
   * Returns the value of the '<em><b>Ich</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ich</em>' containment reference.
   * @see #setIch(IchBlock)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Ich()
   * @model containment="true"
   * @generated
   */
  IchBlock getIch();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getIch <em>Ich</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ich</em>' containment reference.
   * @see #getIch()
   * @generated
   */
  void setIch(IchBlock value);

  /**
   * Returns the value of the '<em><b>Als</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Als</em>' containment reference.
   * @see #setAls(AlsBlock)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Als()
   * @model containment="true"
   * @generated
   */
  AlsBlock getAls();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getAls <em>Als</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Als</em>' containment reference.
   * @see #getAls()
   * @generated
   */
  void setAls(AlsBlock value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' containment reference.
   * @see #setRole(Rolle)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Role()
   * @model containment="true"
   * @generated
   */
  Rolle getRole();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getRole <em>Role</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' containment reference.
   * @see #getRole()
   * @generated
   */
  void setRole(Rolle value);

  /**
   * Returns the value of the '<em><b>Goal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goal</em>' containment reference.
   * @see #setGoal(Ziel)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Goal()
   * @model containment="true"
   * @generated
   */
  Ziel getGoal();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getGoal <em>Goal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Goal</em>' containment reference.
   * @see #getGoal()
   * @generated
   */
  void setGoal(Ziel value);

  /**
   * Returns the value of the '<em><b>Punkt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Punkt</em>' containment reference.
   * @see #setPunkt(PunktBlock)
   * @see de.htwdd.sf.beleg.s86320s86372.beleg.BelegPackage#getUser_Story_Um_Punkt()
   * @model containment="true"
   * @generated
   */
  PunktBlock getPunkt();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s86320s86372.beleg.User_Story_Um#getPunkt <em>Punkt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Punkt</em>' containment reference.
   * @see #getPunkt()
   * @generated
   */
  void setPunkt(PunktBlock value);

} // User_Story_Um
